apiVersion: operator.dash0.com/v1alpha1
kind: Dash0SignalToMetrics
metadata:
  name: error-log-count
spec:
  enabled: true
  display:
    name: Error log records count
  match:
    signal: logs
    filters:
      - key: severity_text
        operator: is_one_of
        values:
          - ERROR
          - FATAL
  output:
    name: log.error.count
    description: Count of error and fatal log records
    interval: 60s
