// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Vendored from the dash0 monorepo
// (modules/proto/internal/decisionmaker/decisionmaker.proto). The vtproto
// extensions (mempool option, vtproto/ext.proto import) have been stripped
// because the e2e mock does not need them and stripping avoids the extra
// dependency.
//
// To re-vendor: copy the upstream file, remove the vtproto import + options,
// then run `make proto-gen-decision-maker-mock` from the repo root.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/decisionmaker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DecisionMakerService_DecisionStream_FullMethodName         = "/decisionmaker.DecisionMakerService/DecisionStream"
	DecisionMakerService_SubscribeServerInfo_FullMethodName    = "/decisionmaker.DecisionMakerService/SubscribeServerInfo"
	DecisionMakerService_SubscribeSamplingRules_FullMethodName = "/decisionmaker.DecisionMakerService/SubscribeSamplingRules"
)

// DecisionMakerServiceClient is the client API for DecisionMakerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DecisionMakerServiceClient interface {
	// DecisionStream provides bidirectional communication for trace decisions.
	// Clients stream satisfaction reports and receive sampling decisions.
	DecisionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TraceReports, TraceDecisions], error)
	// SubscribeServerInfo creates a server-side stream that pushes
	// information about the upstream decision makers. This information can be used to calculate
	// the appropriate distribution of upstream requests.
	SubscribeServerInfo(ctx context.Context, in *SubscribeServerInfoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeServerInfoResponse], error)
	// SubscribeSamplingRules creates a server-side stream that pushes
	// sampling rule definitions for the authenticated organization.
	// Initial response contains all current rules; subsequent messages
	// contain updated rules when changes are detected.
	SubscribeSamplingRules(ctx context.Context, in *SubscribeSamplingRulesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeSamplingRulesResponse], error)
}

type decisionMakerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecisionMakerServiceClient(cc grpc.ClientConnInterface) DecisionMakerServiceClient {
	return &decisionMakerServiceClient{cc}
}

func (c *decisionMakerServiceClient) DecisionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TraceReports, TraceDecisions], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DecisionMakerService_ServiceDesc.Streams[0], DecisionMakerService_DecisionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TraceReports, TraceDecisions]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionMakerService_DecisionStreamClient = grpc.BidiStreamingClient[TraceReports, TraceDecisions]

func (c *decisionMakerServiceClient) SubscribeServerInfo(ctx context.Context, in *SubscribeServerInfoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeServerInfoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DecisionMakerService_ServiceDesc.Streams[1], DecisionMakerService_SubscribeServerInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeServerInfoRequest, SubscribeServerInfoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionMakerService_SubscribeServerInfoClient = grpc.ServerStreamingClient[SubscribeServerInfoResponse]

func (c *decisionMakerServiceClient) SubscribeSamplingRules(ctx context.Context, in *SubscribeSamplingRulesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeSamplingRulesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DecisionMakerService_ServiceDesc.Streams[2], DecisionMakerService_SubscribeSamplingRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeSamplingRulesRequest, SubscribeSamplingRulesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionMakerService_SubscribeSamplingRulesClient = grpc.ServerStreamingClient[SubscribeSamplingRulesResponse]

// DecisionMakerServiceServer is the server API for DecisionMakerService service.
// All implementations must embed UnimplementedDecisionMakerServiceServer
// for forward compatibility.
type DecisionMakerServiceServer interface {
	// DecisionStream provides bidirectional communication for trace decisions.
	// Clients stream satisfaction reports and receive sampling decisions.
	DecisionStream(grpc.BidiStreamingServer[TraceReports, TraceDecisions]) error
	// SubscribeServerInfo creates a server-side stream that pushes
	// information about the upstream decision makers. This information can be used to calculate
	// the appropriate distribution of upstream requests.
	SubscribeServerInfo(*SubscribeServerInfoRequest, grpc.ServerStreamingServer[SubscribeServerInfoResponse]) error
	// SubscribeSamplingRules creates a server-side stream that pushes
	// sampling rule definitions for the authenticated organization.
	// Initial response contains all current rules; subsequent messages
	// contain updated rules when changes are detected.
	SubscribeSamplingRules(*SubscribeSamplingRulesRequest, grpc.ServerStreamingServer[SubscribeSamplingRulesResponse]) error
	mustEmbedUnimplementedDecisionMakerServiceServer()
}

// UnimplementedDecisionMakerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecisionMakerServiceServer struct{}

func (UnimplementedDecisionMakerServiceServer) DecisionStream(grpc.BidiStreamingServer[TraceReports, TraceDecisions]) error {
	return status.Errorf(codes.Unimplemented, "method DecisionStream not implemented")
}
func (UnimplementedDecisionMakerServiceServer) SubscribeServerInfo(*SubscribeServerInfoRequest, grpc.ServerStreamingServer[SubscribeServerInfoResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeServerInfo not implemented")
}
func (UnimplementedDecisionMakerServiceServer) SubscribeSamplingRules(*SubscribeSamplingRulesRequest, grpc.ServerStreamingServer[SubscribeSamplingRulesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeSamplingRules not implemented")
}
func (UnimplementedDecisionMakerServiceServer) mustEmbedUnimplementedDecisionMakerServiceServer() {}
func (UnimplementedDecisionMakerServiceServer) testEmbeddedByValue()                              {}

// UnsafeDecisionMakerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecisionMakerServiceServer will
// result in compilation errors.
type UnsafeDecisionMakerServiceServer interface {
	mustEmbedUnimplementedDecisionMakerServiceServer()
}

func RegisterDecisionMakerServiceServer(s grpc.ServiceRegistrar, srv DecisionMakerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDecisionMakerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DecisionMakerService_ServiceDesc, srv)
}

func _DecisionMakerService_DecisionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DecisionMakerServiceServer).DecisionStream(&grpc.GenericServerStream[TraceReports, TraceDecisions]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionMakerService_DecisionStreamServer = grpc.BidiStreamingServer[TraceReports, TraceDecisions]

func _DecisionMakerService_SubscribeServerInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeServerInfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DecisionMakerServiceServer).SubscribeServerInfo(m, &grpc.GenericServerStream[SubscribeServerInfoRequest, SubscribeServerInfoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionMakerService_SubscribeServerInfoServer = grpc.ServerStreamingServer[SubscribeServerInfoResponse]

func _DecisionMakerService_SubscribeSamplingRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeSamplingRulesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DecisionMakerServiceServer).SubscribeSamplingRules(m, &grpc.GenericServerStream[SubscribeSamplingRulesRequest, SubscribeSamplingRulesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionMakerService_SubscribeSamplingRulesServer = grpc.ServerStreamingServer[SubscribeSamplingRulesResponse]

// DecisionMakerService_ServiceDesc is the grpc.ServiceDesc for DecisionMakerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DecisionMakerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "decisionmaker.DecisionMakerService",
	HandlerType: (*DecisionMakerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DecisionStream",
			Handler:       _DecisionMakerService_DecisionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeServerInfo",
			Handler:       _DecisionMakerService_SubscribeServerInfo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeSamplingRules",
			Handler:       _DecisionMakerService_SubscribeSamplingRules_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/decisionmaker.proto",
}
