// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Vendored from the dash0 monorepo
// (modules/proto/internal/decisionmaker/decisionmaker.proto). The vtproto
// extensions (mempool option, vtproto/ext.proto import) have been stripped
// because the e2e mock does not need them and stripping avoids the extra
// dependency.
//
// To re-vendor: copy the upstream file, remove the vtproto import + options,
// then run `make proto-gen-decision-maker-mock` from the repo root.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/decisionmaker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TraceReports contains one or more trace satisfaction reports (batched).
type TraceReports struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TraceSatisfaction   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceReports) Reset() {
	*x = TraceReports{}
	mi := &file_proto_decisionmaker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceReports) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceReports) ProtoMessage() {}

func (x *TraceReports) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decisionmaker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceReports.ProtoReflect.Descriptor instead.
func (*TraceReports) Descriptor() ([]byte, []int) {
	return file_proto_decisionmaker_proto_rawDescGZIP(), []int{0}
}

func (x *TraceReports) GetItems() []*TraceSatisfaction {
	if x != nil {
		return x.Items
	}
	return nil
}

// TraceDecisions contains one or more trace IDs to persist (batched).
type TraceDecisions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trace IDs that should be sampled (16-byte each).
	TraceId [][]byte `protobuf:"bytes,1,rep,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Rule IDs that triggered each decision (parallel array, rule_id[i] corresponds to trace_id[i]).
	// Optional for backwards compatibility - old decision-makers won't populate this field.
	RuleId        [][]byte `protobuf:"bytes,2,rep,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceDecisions) Reset() {
	*x = TraceDecisions{}
	mi := &file_proto_decisionmaker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceDecisions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceDecisions) ProtoMessage() {}

func (x *TraceDecisions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decisionmaker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceDecisions.ProtoReflect.Descriptor instead.
func (*TraceDecisions) Descriptor() ([]byte, []int) {
	return file_proto_decisionmaker_proto_rawDescGZIP(), []int{1}
}

func (x *TraceDecisions) GetTraceId() [][]byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *TraceDecisions) GetRuleId() [][]byte {
	if x != nil {
		return x.RuleId
	}
	return nil
}

// TraceSatisfaction represents satisfied conditions for a single trace.
type TraceSatisfaction struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TraceId             []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SatisfiedConditions []*Condition           `protobuf:"bytes,2,rep,name=satisfied_conditions,json=satisfiedConditions,proto3" json:"satisfied_conditions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TraceSatisfaction) Reset() {
	*x = TraceSatisfaction{}
	mi := &file_proto_decisionmaker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceSatisfaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceSatisfaction) ProtoMessage() {}

func (x *TraceSatisfaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decisionmaker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceSatisfaction.ProtoReflect.Descriptor instead.
func (*TraceSatisfaction) Descriptor() ([]byte, []int) {
	return file_proto_decisionmaker_proto_rawDescGZIP(), []int{2}
}

func (x *TraceSatisfaction) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *TraceSatisfaction) GetSatisfiedConditions() []*Condition {
	if x != nil {
		return x.SatisfiedConditions
	}
	return nil
}

type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of tail sampling rules
	TailSamplingRuleId []byte `protobuf:"bytes,1,opt,name=tail_sampling_rule_id,json=tailSamplingRuleId,proto3" json:"tail_sampling_rule_id,omitempty"`
	// Which individual condition within the tail-sampling rule was satisfied
	Part          uint32 `protobuf:"varint,2,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_proto_decisionmaker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decisionmaker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_proto_decisionmaker_proto_rawDescGZIP(), []int{3}
}

func (x *Condition) GetTailSamplingRuleId() []byte {
	if x != nil {
		return x.TailSamplingRuleId
	}
	return nil
}

func (x *Condition) GetPart() uint32 {
	if x != nil {
		return x.Part
	}
	return 0
}

type SubscribeServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServerInfoRequest) Reset() {
	*x = SubscribeServerInfoRequest{}
	mi := &file_proto_decisionmaker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServerInfoRequest) ProtoMessage() {}

func (x *SubscribeServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decisionmaker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServerInfoRequest.ProtoReflect.Descriptor instead.
func (*SubscribeServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_decisionmaker_proto_rawDescGZIP(), []int{4}
}

type SubscribeServerInfoResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NumberOfDecisionMakers int32                  `protobuf:"varint,1,opt,name=number_of_decision_makers,json=numberOfDecisionMakers,proto3" json:"number_of_decision_makers,omitempty"`
	// Unique identifier for this decision-maker instance.
	InstanceId    string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServerInfoResponse) Reset() {
	*x = SubscribeServerInfoResponse{}
	mi := &file_proto_decisionmaker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServerInfoResponse) ProtoMessage() {}

func (x *SubscribeServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decisionmaker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServerInfoResponse.ProtoReflect.Descriptor instead.
func (*SubscribeServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_decisionmaker_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeServerInfoResponse) GetNumberOfDecisionMakers() int32 {
	if x != nil {
		return x.NumberOfDecisionMakers
	}
	return 0
}

func (x *SubscribeServerInfoResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type SubscribeSamplingRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeSamplingRulesRequest) Reset() {
	*x = SubscribeSamplingRulesRequest{}
	mi := &file_proto_decisionmaker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeSamplingRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeSamplingRulesRequest) ProtoMessage() {}

func (x *SubscribeSamplingRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decisionmaker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeSamplingRulesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeSamplingRulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_decisionmaker_proto_rawDescGZIP(), []int{6}
}

type SubscribeSamplingRulesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sampling rules for the authenticated organization, one entry per rule.
	Rules         []*SamplingRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeSamplingRulesResponse) Reset() {
	*x = SubscribeSamplingRulesResponse{}
	mi := &file_proto_decisionmaker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeSamplingRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeSamplingRulesResponse) ProtoMessage() {}

func (x *SubscribeSamplingRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decisionmaker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeSamplingRulesResponse.ProtoReflect.Descriptor instead.
func (*SubscribeSamplingRulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_decisionmaker_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeSamplingRulesResponse) GetRules() []*SamplingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SamplingRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization technical ID this rule belongs to.
	OrgTechnicalId string `protobuf:"bytes,1,opt,name=org_technical_id,json=orgTechnicalId,proto3" json:"org_technical_id,omitempty"`
	// Dataset name (from dash0.com/dataset label, empty string for default dataset).
	Dataset string `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	// SamplingDefinition serialized as JSON bytes.
	SamplingDefinitionJson []byte `protobuf:"bytes,3,opt,name=sampling_definition_json,json=samplingDefinitionJson,proto3" json:"sampling_definition_json,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SamplingRule) Reset() {
	*x = SamplingRule{}
	mi := &file_proto_decisionmaker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingRule) ProtoMessage() {}

func (x *SamplingRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_decisionmaker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingRule.ProtoReflect.Descriptor instead.
func (*SamplingRule) Descriptor() ([]byte, []int) {
	return file_proto_decisionmaker_proto_rawDescGZIP(), []int{8}
}

func (x *SamplingRule) GetOrgTechnicalId() string {
	if x != nil {
		return x.OrgTechnicalId
	}
	return ""
}

func (x *SamplingRule) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *SamplingRule) GetSamplingDefinitionJson() []byte {
	if x != nil {
		return x.SamplingDefinitionJson
	}
	return nil
}

var File_proto_decisionmaker_proto protoreflect.FileDescriptor

const file_proto_decisionmaker_proto_rawDesc = "" +
	"\n" +
	"\x19proto/decisionmaker.proto\x12\rdecisionmaker\"F\n" +
	"\fTraceReports\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .decisionmaker.TraceSatisfactionR\x05items\"D\n" +
	"\x0eTraceDecisions\x12\x19\n" +
	"\btrace_id\x18\x01 \x03(\fR\atraceId\x12\x17\n" +
	"\arule_id\x18\x02 \x03(\fR\x06ruleId\"{\n" +
	"\x11TraceSatisfaction\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12K\n" +
	"\x14satisfied_conditions\x18\x02 \x03(\v2\x18.decisionmaker.ConditionR\x13satisfiedConditions\"R\n" +
	"\tCondition\x121\n" +
	"\x15tail_sampling_rule_id\x18\x01 \x01(\fR\x12tailSamplingRuleId\x12\x12\n" +
	"\x04part\x18\x02 \x01(\rR\x04part\"\x1c\n" +
	"\x1aSubscribeServerInfoRequest\"y\n" +
	"\x1bSubscribeServerInfoResponse\x129\n" +
	"\x19number_of_decision_makers\x18\x01 \x01(\x05R\x16numberOfDecisionMakers\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"\x1f\n" +
	"\x1dSubscribeSamplingRulesRequest\"S\n" +
	"\x1eSubscribeSamplingRulesResponse\x121\n" +
	"\x05rules\x18\x01 \x03(\v2\x1b.decisionmaker.SamplingRuleR\x05rules\"\x8c\x01\n" +
	"\fSamplingRule\x12(\n" +
	"\x10org_technical_id\x18\x01 \x01(\tR\x0eorgTechnicalId\x12\x18\n" +
	"\adataset\x18\x02 \x01(\tR\adataset\x128\n" +
	"\x18sampling_definition_json\x18\x03 \x01(\fR\x16samplingDefinitionJson2\xd1\x02\n" +
	"\x14DecisionMakerService\x12P\n" +
	"\x0eDecisionStream\x12\x1b.decisionmaker.TraceReports\x1a\x1d.decisionmaker.TraceDecisions(\x010\x01\x12n\n" +
	"\x13SubscribeServerInfo\x12).decisionmaker.SubscribeServerInfoRequest\x1a*.decisionmaker.SubscribeServerInfoResponse0\x01\x12w\n" +
	"\x16SubscribeSamplingRules\x12,.decisionmaker.SubscribeSamplingRulesRequest\x1a-.decisionmaker.SubscribeSamplingRulesResponse0\x01B\x1bZ\x19decision-maker-mock/protob\x06proto3"

var (
	file_proto_decisionmaker_proto_rawDescOnce sync.Once
	file_proto_decisionmaker_proto_rawDescData []byte
)

func file_proto_decisionmaker_proto_rawDescGZIP() []byte {
	file_proto_decisionmaker_proto_rawDescOnce.Do(func() {
		file_proto_decisionmaker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_decisionmaker_proto_rawDesc), len(file_proto_decisionmaker_proto_rawDesc)))
	})
	return file_proto_decisionmaker_proto_rawDescData
}

var file_proto_decisionmaker_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_decisionmaker_proto_goTypes = []any{
	(*TraceReports)(nil),                   // 0: decisionmaker.TraceReports
	(*TraceDecisions)(nil),                 // 1: decisionmaker.TraceDecisions
	(*TraceSatisfaction)(nil),              // 2: decisionmaker.TraceSatisfaction
	(*Condition)(nil),                      // 3: decisionmaker.Condition
	(*SubscribeServerInfoRequest)(nil),     // 4: decisionmaker.SubscribeServerInfoRequest
	(*SubscribeServerInfoResponse)(nil),    // 5: decisionmaker.SubscribeServerInfoResponse
	(*SubscribeSamplingRulesRequest)(nil),  // 6: decisionmaker.SubscribeSamplingRulesRequest
	(*SubscribeSamplingRulesResponse)(nil), // 7: decisionmaker.SubscribeSamplingRulesResponse
	(*SamplingRule)(nil),                   // 8: decisionmaker.SamplingRule
}
var file_proto_decisionmaker_proto_depIdxs = []int32{
	2, // 0: decisionmaker.TraceReports.items:type_name -> decisionmaker.TraceSatisfaction
	3, // 1: decisionmaker.TraceSatisfaction.satisfied_conditions:type_name -> decisionmaker.Condition
	8, // 2: decisionmaker.SubscribeSamplingRulesResponse.rules:type_name -> decisionmaker.SamplingRule
	0, // 3: decisionmaker.DecisionMakerService.DecisionStream:input_type -> decisionmaker.TraceReports
	4, // 4: decisionmaker.DecisionMakerService.SubscribeServerInfo:input_type -> decisionmaker.SubscribeServerInfoRequest
	6, // 5: decisionmaker.DecisionMakerService.SubscribeSamplingRules:input_type -> decisionmaker.SubscribeSamplingRulesRequest
	1, // 6: decisionmaker.DecisionMakerService.DecisionStream:output_type -> decisionmaker.TraceDecisions
	5, // 7: decisionmaker.DecisionMakerService.SubscribeServerInfo:output_type -> decisionmaker.SubscribeServerInfoResponse
	7, // 8: decisionmaker.DecisionMakerService.SubscribeSamplingRules:output_type -> decisionmaker.SubscribeSamplingRulesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_decisionmaker_proto_init() }
func file_proto_decisionmaker_proto_init() {
	if File_proto_decisionmaker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_decisionmaker_proto_rawDesc), len(file_proto_decisionmaker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_decisionmaker_proto_goTypes,
		DependencyIndexes: file_proto_decisionmaker_proto_depIdxs,
		MessageInfos:      file_proto_decisionmaker_proto_msgTypes,
	}.Build()
	File_proto_decisionmaker_proto = out.File
	file_proto_decisionmaker_proto_goTypes = nil
	file_proto_decisionmaker_proto_depIdxs = nil
}
