//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0Team) DeepCopyInto(out *Dash0Team) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0Team.
func (in *Dash0Team) DeepCopy() *Dash0Team {
	if in == nil {
		return nil
	}
	out := new(Dash0Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0Team) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0TeamColor) DeepCopyInto(out *Dash0TeamColor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0TeamColor.
func (in *Dash0TeamColor) DeepCopy() *Dash0TeamColor {
	if in == nil {
		return nil
	}
	out := new(Dash0TeamColor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0TeamDisplay) DeepCopyInto(out *Dash0TeamDisplay) {
	*out = *in
	out.Color = in.Color
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0TeamDisplay.
func (in *Dash0TeamDisplay) DeepCopy() *Dash0TeamDisplay {
	if in == nil {
		return nil
	}
	out := new(Dash0TeamDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0TeamList) DeepCopyInto(out *Dash0TeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0Team, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0TeamList.
func (in *Dash0TeamList) DeepCopy() *Dash0TeamList {
	if in == nil {
		return nil
	}
	out := new(Dash0TeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0TeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0TeamSpec) DeepCopyInto(out *Dash0TeamSpec) {
	*out = *in
	out.Display = in.Display
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0TeamSpec.
func (in *Dash0TeamSpec) DeepCopy() *Dash0TeamSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0TeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0TeamStatus) DeepCopyInto(out *Dash0TeamStatus) {
	*out = *in
	in.SynchronizedAt.DeepCopyInto(&out.SynchronizedAt)
	if in.ValidationIssues != nil {
		in, out := &in.ValidationIssues, &out.ValidationIssues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SynchronizationResults != nil {
		in, out := &in.SynchronizationResults, &out.SynchronizationResults
		*out = make([]Dash0TeamSynchronizationResultPerEndpointAndDataset, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0TeamStatus.
func (in *Dash0TeamStatus) DeepCopy() *Dash0TeamStatus {
	if in == nil {
		return nil
	}
	out := new(Dash0TeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0TeamSynchronizationResultPerEndpointAndDataset) DeepCopyInto(out *Dash0TeamSynchronizationResultPerEndpointAndDataset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0TeamSynchronizationResultPerEndpointAndDataset.
func (in *Dash0TeamSynchronizationResultPerEndpointAndDataset) DeepCopy() *Dash0TeamSynchronizationResultPerEndpointAndDataset {
	if in == nil {
		return nil
	}
	out := new(Dash0TeamSynchronizationResultPerEndpointAndDataset)
	in.DeepCopyInto(out)
	return out
}
