apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: ubuntu
      app.kubernetes.io/part-of: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ubuntu
        app.kubernetes.io/version: "1.2.3"
        app.kubernetes.io/part-of: test
        app.kubernetes.io/instance: the-one-buntu
      annotations:
        resource.opentelemetry.io/foo: bar
        resource.opentelemetry.io/foz: baz
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent