apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
    app.kubernetes.io/name: ubuntu
    app.kubernetes.io/version: "1.2.3"
    app.kubernetes.io/part-of: test
    app.kubernetes.io/instance: the-one-buntu
  annotations:
    resource.opentelemetry.io/foo: bar
    resource.opentelemetry.io/foz: baz
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always