apiVersion: operator.dash0.com/v1beta1
kind: Dash0NotificationChannel
metadata:
  name: operator-test-opsgenie
spec:
  display:
    name: OpsGenie Alerts
  type: opsgenie
  opsgenieConfig:
    instance: eu
    apiKey: "00000000-0000-0000-0000-000000000000"
  frequency: 10m
