# SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: ruby-rails-demo-svc
spec:
  selector:
    app: ruby-rails-demo
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP
