# SPDX-FileCopyrightText: Copyright 2024 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: dash0-operator-jvm-spring-boot-test-replicaset-service
spec:
  selector:
    app: dash0-operator-jvm-spring-boot-test-replicaset-app
  ports:
    - port: 1309
      targetPort: 1309
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dash0-operator-jvm-spring-boot-test-replicaset
  labels:
    app: dash0-operator-jvm-spring-boot-test-replicaset-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash0-operator-jvm-spring-boot-test-replicaset-app
  template:
    metadata:
      labels:
        app: dash0-operator-jvm-spring-boot-test-replicaset-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1309"
    spec:
      containers:
        - name: dash0-operator-jvm-spring-boot-test-replicaset-app
          image: "dash0-operator-jvm-spring-boot-test-app:latest"
          env:
            - name: PORT
              value: "1309"
            - name: DASH0_DEBUG
              value: "true"
          ports:
            - containerPort: 1309
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: 1309
            initialDelaySeconds: 1
            periodSeconds: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash0-operator-jvm-spring-boot-test-replicaset-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /replicaset(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dash0-operator-jvm-spring-boot-test-replicaset-service
            port:
              number: 1309
