//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package common

import (
	"encoding/json"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authorization) DeepCopyInto(out *Authorization) {
	*out = *in
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authorization.
func (in *Authorization) DeepCopy() *Authorization {
	if in == nil {
		return nil
	}
	out := new(Authorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0Configuration) DeepCopyInto(out *Dash0Configuration) {
	*out = *in
	in.Authorization.DeepCopyInto(&out.Authorization)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0Configuration.
func (in *Dash0Configuration) DeepCopy() *Dash0Configuration {
	if in == nil {
		return nil
	}
	out := new(Dash0Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventCollection) DeepCopyInto(out *EventCollection) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventCollection.
func (in *EventCollection) DeepCopy() *EventCollection {
	if in == nil {
		return nil
	}
	out := new(EventCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Export) DeepCopyInto(out *Export) {
	*out = *in
	if in.Dash0 != nil {
		in, out := &in.Dash0, &out.Dash0
		*out = new(Dash0Configuration)
		(*in).DeepCopyInto(*out)
	}
	if in.Http != nil {
		in, out := &in.Http, &out.Http
		*out = new(HttpConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Grpc != nil {
		in, out := &in.Grpc, &out.Grpc
		*out = new(GrpcConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Export.
func (in *Export) DeepCopy() *Export {
	if in == nil {
		return nil
	}
	out := new(Export)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	if in.Traces != nil {
		in, out := &in.Traces, &out.Traces
		*out = new(TraceFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(LogFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrpcConfiguration) DeepCopyInto(out *GrpcConfiguration) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]Header, len(*in))
		copy(*out, *in)
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrpcConfiguration.
func (in *GrpcConfiguration) DeepCopy() *GrpcConfiguration {
	if in == nil {
		return nil
	}
	out := new(GrpcConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Header) DeepCopyInto(out *Header) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Header.
func (in *Header) DeepCopy() *Header {
	if in == nil {
		return nil
	}
	out := new(Header)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpConfiguration) DeepCopyInto(out *HttpConfiguration) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]Header, len(*in))
		copy(*out, *in)
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpConfiguration.
func (in *HttpConfiguration) DeepCopy() *HttpConfiguration {
	if in == nil {
		return nil
	}
	out := new(HttpConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogCollection) DeepCopyInto(out *LogCollection) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Multiline != nil {
		in, out := &in.Multiline, &out.Multiline
		*out = new(MultilineConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogCollection.
func (in *LogCollection) DeepCopy() *LogCollection {
	if in == nil {
		return nil
	}
	out := new(LogCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogFilter) DeepCopyInto(out *LogFilter) {
	*out = *in
	if in.LogRecordFilter != nil {
		in, out := &in.LogRecordFilter, &out.LogRecordFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogFilter.
func (in *LogFilter) DeepCopy() *LogFilter {
	if in == nil {
		return nil
	}
	out := new(LogFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricFilter) DeepCopyInto(out *MetricFilter) {
	*out = *in
	if in.MetricFilter != nil {
		in, out := &in.MetricFilter, &out.MetricFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataPointFilter != nil {
		in, out := &in.DataPointFilter, &out.DataPointFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricFilter.
func (in *MetricFilter) DeepCopy() *MetricFilter {
	if in == nil {
		return nil
	}
	out := new(MetricFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultilineConfig) DeepCopyInto(out *MultilineConfig) {
	*out = *in
	if in.LineStartPattern != nil {
		in, out := &in.LineStartPattern, &out.LineStartPattern
		*out = new(string)
		**out = **in
	}
	if in.LineEndPattern != nil {
		in, out := &in.LineEndPattern, &out.LineEndPattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultilineConfig.
func (in *MultilineConfig) DeepCopy() *MultilineConfig {
	if in == nil {
		return nil
	}
	out := new(MultilineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizedTransformGroup) DeepCopyInto(out *NormalizedTransformGroup) {
	*out = *in
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = new(string)
		**out = **in
	}
	if in.ErrorMode != nil {
		in, out := &in.ErrorMode, &out.ErrorMode
		*out = new(FilterTransformErrorMode)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Statements != nil {
		in, out := &in.Statements, &out.Statements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizedTransformGroup.
func (in *NormalizedTransformGroup) DeepCopy() *NormalizedTransformGroup {
	if in == nil {
		return nil
	}
	out := new(NormalizedTransformGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizedTransformSpec) DeepCopyInto(out *NormalizedTransformSpec) {
	*out = *in
	if in.ErrorMode != nil {
		in, out := &in.ErrorMode, &out.ErrorMode
		*out = new(FilterTransformErrorMode)
		**out = **in
	}
	if in.Traces != nil {
		in, out := &in.Traces, &out.Traces
		*out = make([]NormalizedTransformGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]NormalizedTransformGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = make([]NormalizedTransformGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizedTransformSpec.
func (in *NormalizedTransformSpec) DeepCopy() *NormalizedTransformSpec {
	if in == nil {
		return nil
	}
	out := new(NormalizedTransformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesDashboardSynchronizationResults) DeepCopyInto(out *PersesDashboardSynchronizationResults) {
	*out = *in
	in.SynchronizedAt.DeepCopyInto(&out.SynchronizedAt)
	if in.ValidationIssues != nil {
		in, out := &in.ValidationIssues, &out.ValidationIssues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesDashboardSynchronizationResults.
func (in *PersesDashboardSynchronizationResults) DeepCopy() *PersesDashboardSynchronizationResults {
	if in == nil {
		return nil
	}
	out := new(PersesDashboardSynchronizationResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusRuleSynchronizationResult) DeepCopyInto(out *PrometheusRuleSynchronizationResult) {
	*out = *in
	in.SynchronizedAt.DeepCopyInto(&out.SynchronizedAt)
	if in.SynchronizedRulesAttributes != nil {
		in, out := &in.SynchronizedRulesAttributes, &out.SynchronizedRulesAttributes
		*out = make(map[string]PrometheusRuleSynchronizedRuleAttributes, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SynchronizationErrors != nil {
		in, out := &in.SynchronizationErrors, &out.SynchronizationErrors
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InvalidRules != nil {
		in, out := &in.InvalidRules, &out.InvalidRules
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusRuleSynchronizationResult.
func (in *PrometheusRuleSynchronizationResult) DeepCopy() *PrometheusRuleSynchronizationResult {
	if in == nil {
		return nil
	}
	out := new(PrometheusRuleSynchronizationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusRuleSynchronizedRuleAttributes) DeepCopyInto(out *PrometheusRuleSynchronizedRuleAttributes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusRuleSynchronizedRuleAttributes.
func (in *PrometheusRuleSynchronizedRuleAttributes) DeepCopy() *PrometheusRuleSynchronizedRuleAttributes {
	if in == nil {
		return nil
	}
	out := new(PrometheusRuleSynchronizedRuleAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusScraping) DeepCopyInto(out *PrometheusScraping) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusScraping.
func (in *PrometheusScraping) DeepCopy() *PrometheusScraping {
	if in == nil {
		return nil
	}
	out := new(PrometheusScraping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceFilter) DeepCopyInto(out *TraceFilter) {
	*out = *in
	if in.SpanFilter != nil {
		in, out := &in.SpanFilter, &out.SpanFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SpanEventFilter != nil {
		in, out := &in.SpanEventFilter, &out.SpanEventFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceFilter.
func (in *TraceFilter) DeepCopy() *TraceFilter {
	if in == nil {
		return nil
	}
	out := new(TraceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transform) DeepCopyInto(out *Transform) {
	*out = *in
	if in.ErrorMode != nil {
		in, out := &in.ErrorMode, &out.ErrorMode
		*out = new(FilterTransformErrorMode)
		**out = **in
	}
	if in.Traces != nil {
		in, out := &in.Traces, &out.Traces
		*out = make([]json.RawMessage, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(json.RawMessage, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]json.RawMessage, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(json.RawMessage, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = make([]json.RawMessage, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(json.RawMessage, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transform.
func (in *Transform) DeepCopy() *Transform {
	if in == nil {
		return nil
	}
	out := new(Transform)
	in.DeepCopyInto(out)
	return out
}
