# SPDX-FileCopyrightText: Copyright 2024 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:24.10

RUN apt update && \
  apt-get install -y \
    build-essential

WORKDIR /usr/src/dash0/preload/

CMD ["scripts/make-clean.sh"]
