//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLO) DeepCopyInto(out *SLO) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLO.
func (in *SLO) DeepCopy() *SLO {
	if in == nil {
		return nil
	}
	out := new(SLO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SLO) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOIndicator) DeepCopyInto(out *SLOIndicator) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(SLOIndicatorMetadata)
		**out = **in
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOIndicator.
func (in *SLOIndicator) DeepCopy() *SLOIndicator {
	if in == nil {
		return nil
	}
	out := new(SLOIndicator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOIndicatorMetadata) DeepCopyInto(out *SLOIndicatorMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOIndicatorMetadata.
func (in *SLOIndicatorMetadata) DeepCopy() *SLOIndicatorMetadata {
	if in == nil {
		return nil
	}
	out := new(SLOIndicatorMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOIndicatorSpec) DeepCopyInto(out *SLOIndicatorSpec) {
	*out = *in
	in.RatioMetric.DeepCopyInto(&out.RatioMetric)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOIndicatorSpec.
func (in *SLOIndicatorSpec) DeepCopy() *SLOIndicatorSpec {
	if in == nil {
		return nil
	}
	out := new(SLOIndicatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOList) DeepCopyInto(out *SLOList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SLO, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOList.
func (in *SLOList) DeepCopy() *SLOList {
	if in == nil {
		return nil
	}
	out := new(SLOList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SLOList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOMetricSource) DeepCopyInto(out *SLOMetricSource) {
	*out = *in
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOMetricSource.
func (in *SLOMetricSource) DeepCopy() *SLOMetricSource {
	if in == nil {
		return nil
	}
	out := new(SLOMetricSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOMetricSourceSpec) DeepCopyInto(out *SLOMetricSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOMetricSourceSpec.
func (in *SLOMetricSourceSpec) DeepCopy() *SLOMetricSourceSpec {
	if in == nil {
		return nil
	}
	out := new(SLOMetricSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOMetricSourceWrapper) DeepCopyInto(out *SLOMetricSourceWrapper) {
	*out = *in
	out.MetricSource = in.MetricSource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOMetricSourceWrapper.
func (in *SLOMetricSourceWrapper) DeepCopy() *SLOMetricSourceWrapper {
	if in == nil {
		return nil
	}
	out := new(SLOMetricSourceWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOObjective) DeepCopyInto(out *SLOObjective) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOObjective.
func (in *SLOObjective) DeepCopy() *SLOObjective {
	if in == nil {
		return nil
	}
	out := new(SLOObjective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLORatioMetric) DeepCopyInto(out *SLORatioMetric) {
	*out = *in
	if in.Counter != nil {
		in, out := &in.Counter, &out.Counter
		*out = new(bool)
		**out = **in
	}
	out.Good = in.Good
	out.Total = in.Total
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLORatioMetric.
func (in *SLORatioMetric) DeepCopy() *SLORatioMetric {
	if in == nil {
		return nil
	}
	out := new(SLORatioMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOSpec) DeepCopyInto(out *SLOSpec) {
	*out = *in
	if in.TimeWindow != nil {
		in, out := &in.TimeWindow, &out.TimeWindow
		*out = make([]SLOTimeWindow, len(*in))
		copy(*out, *in)
	}
	in.Indicator.DeepCopyInto(&out.Indicator)
	if in.Objectives != nil {
		in, out := &in.Objectives, &out.Objectives
		*out = make([]SLOObjective, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOSpec.
func (in *SLOSpec) DeepCopy() *SLOSpec {
	if in == nil {
		return nil
	}
	out := new(SLOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOStatus) DeepCopyInto(out *SLOStatus) {
	*out = *in
	in.SynchronizedAt.DeepCopyInto(&out.SynchronizedAt)
	if in.ValidationIssues != nil {
		in, out := &in.ValidationIssues, &out.ValidationIssues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SynchronizationResults != nil {
		in, out := &in.SynchronizationResults, &out.SynchronizationResults
		*out = make([]SLOSynchronizationResultPerEndpointAndDataset, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOStatus.
func (in *SLOStatus) DeepCopy() *SLOStatus {
	if in == nil {
		return nil
	}
	out := new(SLOStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOSynchronizationResultPerEndpointAndDataset) DeepCopyInto(out *SLOSynchronizationResultPerEndpointAndDataset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOSynchronizationResultPerEndpointAndDataset.
func (in *SLOSynchronizationResultPerEndpointAndDataset) DeepCopy() *SLOSynchronizationResultPerEndpointAndDataset {
	if in == nil {
		return nil
	}
	out := new(SLOSynchronizationResultPerEndpointAndDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOTimeWindow) DeepCopyInto(out *SLOTimeWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOTimeWindow.
func (in *SLOTimeWindow) DeepCopy() *SLOTimeWindow {
	if in == nil {
		return nil
	}
	out := new(SLOTimeWindow)
	in.DeepCopyInto(out)
	return out
}
