name: build container image
description: builds and pushes a container image

inputs:
  githubToken:
    description: "github token"
    required: true
  slackBotToken:
    description: "slackbot token"
    required: true
  slackChannelId:
    description: "slack channel id"
    required: true
  imageName:
    description: "name of the container image (without registry prefix)"
    required: true
  imageTitle:
    description: "human-readable title for the container image metadata"
    required: true
  imageDescription:
    description: "human-readable description for the container image metadata"
    required: true
  imageUrl:
    description: "URL for the sources of the image"
    required: true
  context:
    description: "docker build context directory"
    required: true
  file:
    description: "path to dockerfile, defaults to ${context}/Dockerfile"
    required: false
    default: ''
  scan:
    description: "whether to scan the built image with Trivy"
    required: false
    default: 'false'
  scanSeverity:
    description: "severity setting for the Trivy scanner, see https://trivy.dev/docs/latest/guide/configuration/filtering/#by-severity"
    required: false
    default: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
  exitCode:
    description: "the exit code in case a cve is found, use this setting to control whether the build should fail or not"
    required: false
    default: '0'

runs:
  using: "composite"
  steps:

    - name: set up docker buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

    - name: login to GitHub container registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.githubToken }}

    - name: extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
      with:
        images: |
          ghcr.io/dash0hq/${{ inputs.imageName }}
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,enable={{is_default_branch}},suffix=-dev,event=branch
          type=ref,event=tag
          type=sha
        labels: |
          org.opencontainers.image.title=${{ inputs.imageTitle }}
          org.opencontainers.image.description=${{ inputs.imageDescription }}
          org.opencontainers.image.vendor=Dash0 Inc.
          org.opencontainers.image.url=${{ inputs.imageUrl }}
        flavor: |
          latest=auto

    - name: determine whether to push the image
      id: determine-push
      shell: bash
      run: |
        if [[ $GITHUB_REF == 'refs/heads/main' || $GITHUB_REF == *"refs/tags/"* ]]; then
          echo "PUSH_ENABLED=true" >> "$GITHUB_ENV"
        else
          echo "PUSH_ENABLED=false" >> "$GITHUB_ENV"
        fi

    - name: build container image
      id: docker-build
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file != '' && inputs.file || format('{0}/Dockerfile', inputs.context) }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # Maintenance note: When not pushing only building amd64 is enough to verify the image can be built,
        # and it is much faster than building both platforms.
        platforms: 'linux/amd64'
        cache-from: type=gha,scope=${{ inputs.imageName }}
        cache-to: type=gha,mode=max,scope=${{ inputs.imageName }}
        load: true
        push: false

    # optionally scan the built container image with Trivy and upload the results
    - name: run Trivy vulnerability scanner
      if: ${{ inputs.scan == 'true' }}
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: '${{ steps.docker-build.outputs.imageid }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: ${{ inputs.exitCode }}
        severity: ${{ inputs.scanSeverity }}
        limit-severities-for-sarif: true

    # The scan results are also available at https://github.com/dash0hq/dash0-operator/security/code-scanning with
    # query "is:open pr:xyz", but having them in the build log is just also handy sometimes.
    - name: echo sarif file
      if: ${{ always() && inputs.scan == 'true' }}
      shell: bash
      run: |
        cat trivy-results.sarif

    - name: upload Trivy scan results to GitHub Security tab
      if: ${{ always() && inputs.scan == 'true' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
        category: ".github/workflows/ci.yaml:build_and_push_images/${{ inputs.imageName }}"

    - name: check Trivy results for vulnerabilities
      id: trivy-check
      if: ${{ always() && inputs.scan == 'true' }}
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          echo "jq not found"
          exit 1
        fi
        VULN_COUNT=$(jq '[.runs[]?.results[]?] | length' trivy-results.sarif)
        echo "vulnerability_count=$VULN_COUNT" >> "$GITHUB_OUTPUT"
        echo "has_vulnerabilities=$( [ "$VULN_COUNT" -gt 0 ] && echo true || echo false )" >> "$GITHUB_OUTPUT"

    - name: send Slack notification in case of vulnerabilities
      if: ${{ always() && steps.trivy-check.outputs.has_vulnerabilities == 'true' }}
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a
      with:
        errors: true
        method: chat.postMessage
        token: ${{ inputs.slackBotToken }}
        # language=YAML
        payload: |
          channel: ${{ inputs.slackChannelId }}
          text: 'Trivy scan failed: vulnerabilities found or issues running the scan'
          blocks:
            - type: header
              text:
                type: plain_text
                text: ':x: Trivy scan failed: vulnerabilities found or issues running the scan'
            - type: context
              elements:
                - type: mrkdwn
                  text: ':github: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow run #${{ github.run_id }}>'
                - type: mrkdwn
                  text: ':diff: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|Commit>'
                - type: mrkdwn
                  text: ':seedling: <${{ github.server_url }}/${{ github.repository }}/tree/${{ github.head_ref || github.ref_name }}|${{ github.head_ref || github.ref_name }}>'
                - type: mrkdwn
                  text: ':package: ${{ inputs.imageName }}'
                - type: mrkdwn
                  text: ':warning: ${{ steps.trivy-check.outputs.vulnerability_count }} CVE(s) found'
                - type: mrkdwn
                  text: ':mag: <${{ github.server_url }}/${{ github.repository }}/security/code-scanning?query=ref%3A${{ github.head_ref || github.ref_name }}+tool%3ATrivy|Scan result>'

    - name: push container image
      if: ${{ env.PUSH_ENABLED == 'true' }}
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file != '' && inputs.file || format('{0}/Dockerfile', inputs.context) }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: 'linux/amd64,linux/arm64'
        cache-from: type=gha,scope=${{ inputs.imageName }}
        cache-to: type=gha,mode=max,scope=${{ inputs.imageName }}
        push: ${{ env.PUSH_ENABLED }}
