apiVersion: operator.dash0.com/v1alpha1
kind: Dash0Monitoring
metadata:
  name: dash0-monitoring-resource
spec:
  # production: endpoint: ingress.eu-west-1.aws.dash0.com:4317
  # development: ingress.eu-west-1.aws.dash0-dev.com:4317
  endpoint: ingress.eu-west-1.aws.dash0-dev.com:4317

  # Either provide the name of a secret existing in the Dash0 operator's namespace as secretRef:
  secretRef: dash0-authorization-secret

  # Or provide the token directly as authorizationToken:
  # authorizationToken: auth_...

  # Opt-out settings for particular use cases. The default value is "all". Other possible values are
  # "created-and-updated" and "none".
  # instrumentWorkloads: all

