---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0monitorings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0monitorings/finalizers
  verbs:
  - update
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0monitorings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0operatorconfigurations
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0operatorconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0operatorconfigurations/status
  verbs:
  - get
  - patch
  - update
