apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-base
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cluster-role-binding-base
    {{- include "dash0-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dash0-operator.chartName" . }}-manager-base
subjects:
- kind: ServiceAccount
  name: {{ template "dash0-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-iac
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cluster-role-binding-iac
    {{- include "dash0-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dash0-operator.chartName" . }}-manager-iac
subjects:
- kind: ServiceAccount
  name: {{ template "dash0-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---
{{ if .Values.operator.telemetryCollectionEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-collector
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cluster-role-binding-collector
    {{- include "dash0-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dash0-operator.chartName" . }}-manager-collector
subjects:
- kind: ServiceAccount
  name: {{ template "dash0-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}

---
{{ if .Values.operator.telemetryCollectionEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-instrument
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cluster-role-binding-instrument
    {{- include "dash0-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dash0-operator.chartName" . }}-manager-instrument
subjects:
- kind: ServiceAccount
  name: {{ template "dash0-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
