apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    {{- include "dash0-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dash0-operator.chartName" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "dash0-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dash0-operator.chartName" . }}-proxy-rolebinding
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/component: kube-rbac-proxy
    {{- include "dash0-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dash0-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ template "dash0-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
