{{/*
The -manager-base cluster role holds permissions required for basic operator manager tasks.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-base
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cluster-role-base
    {{- include "dash0-operator.labels" . | nindent 4 }}

rules:

# Permissions required to manage the Dash0 operator configuration resource, its finalizers and status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0operatorconfigurations
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

# Permissions required to manage the Dash0 operator configuration resource, its finalizers and status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0operatorconfigurations/finalizers
  verbs:
  - update

# Permissions required to manage the Dash0 operator configuration resource, its finalizers and status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0operatorconfigurations/status
  verbs:
  - get
  - patch
  - update

# Permissions required to manage the Dash0 monitoring resource, its finalizers and status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0monitorings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

# Permissions required to manage the Dash0 monitoring resource, its finalizers and status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0monitorings/finalizers
  verbs:
  - update

# Permissions required to manage the Dash0 monitoring resource, its finalizers and status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0monitorings/status
  verbs:
  - get
  - patch
  - update

# Permissions required to queue events to report about the operator's actions:
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get

# Permissions for the legacy event API, required to attach dangling events to their respective involved objects:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - patch
  - update

# Permissions required to detect the container runtime:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list

---
{{/*
The -manager-iac cluster role holds permissions used for IaC tasks, like synchronizing dashboards and check rules.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-iac
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cluster-role-iac
    {{- include "dash0-operator.labels" . | nindent 4 }}

rules:

# Permissions required to watch for the third-party CRD (Perses dashboards, Prometheus check rules):
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch

# Permissions required to watch Perses dashboard resources:
- apiGroups:
  - perses.dev
  resources:
  - persesdashboards
  verbs:
  - get
  - list
  - watch

# Permissions required to watch Prometheus rule resources:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - get
  - list
  - watch

# Permissions required to watch Dash0 synthetic check resources:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0syntheticchecks
  verbs:
  - get
  - list
  - watch

# Permissions required to write to Dash0 synthetic check resource status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0syntheticchecks/status
  verbs:
  - get
  - patch
  - update

# Permissions required to watch Dash0 view resources:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0views
  verbs:
  - get
  - list
  - watch

# Permissions required to write to Dash0 view resource status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0views/status
  verbs:
  - get
  - patch
  - update

# Permissions required to manage the Dash0 intelligent edge resource, its finalizers and status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0intelligentedges
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - operator.dash0.com
  resources:
  - dash0intelligentedges/finalizers
  verbs:
  - update

- apiGroups:
  - operator.dash0.com
  resources:
  - dash0intelligentedges/status
  verbs:
  - get
  - patch
  - update

# Permissions required to watch Dash0 sampling rule resources:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0samplingrules
  verbs:
  - get
  - list
  - watch

# Permissions required to write to Dash0 sampling rule resource status:
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0samplingrules/status
  verbs:
  - get
  - patch
  - update

---
{{ if .Values.operator.telemetryCollectionEnabled }}
{{/*
The -manager-collector cluster role holds permissions for managing OpenTelemetry collectors and the target allocator.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-collector
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cluster-role-collector
    {{- include "dash0-operator.labels" . | nindent 4 }}

rules:

# Permissions required to manage OTel collector resources:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  # Note: apps.daemonsets and app.deployments are also listed further up together with the other workload types in the
  # apps API group, with fewer permissions. The declaration here extends that list of permissions to make sure we can
  # also create and delete the daemonset and deployment for the OTel collector instance that the Dash0 operator
  # manages.
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Permissions required due to the fact that the operator needs to create dedicated service accounts/cluster roles/
# cluster role bindings for the OTel collector daemonset/deployment and give it a set of permissions; which it can only
# do if holds these permissions itself.
#
# First, the permissions for the OpenTelemetry collector DaemonSet:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - persistentvolumes
  - persistentvolumeclaims
  - namespaces
  - nodes
  - nodes/stats
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
# Next, the permissions for the OpenTelemetry collector Deployment:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - namespaces/status
  - nodes
  - nodes/spec
  - pods
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/status
  - resourcequotas
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch

# Permissions required due to the fact that the operator needs to create dedicated service accounts/cluster roles/
# cluster role bindings for the OTel target-allocator and give it a set of permissions; which it can only
# do if holds these permissions itself.
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - probes
  - prometheusrules
  - scrapeconfigs
  - servicemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - nodes/metrics
  - services
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get

{{ end }}

---
{{ if .Values.operator.telemetryCollectionEnabled }}
{{/*
The -manager-instrument cluster role holds permissions necessary for auto-instrumenting workloads.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-instrument
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cluster-role-instrument
    {{- include "dash0-operator.labels" . | nindent 4 }}

rules:

# Permissions required to instrument workloads in the apps API group:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch

# Permissions required to instrument workloads in the batch API group:
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch

# Permissions required to automatically restart (i.e. delete) pods when instrumenting replicasets that are not part of a
# higher order workload (e.g. a deployment, daemonset):
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list

{{ end }}
