apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dash0-operator.chartName" . }}-manager-role
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: manager-role
    {{- include "dash0-operator.labels" . | nindent 4 }}

rules:

# Permissions required to instrument workloads in the apps API group.
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch

# Permissions required to instrument workloads in the batch API group.
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch

# Permissions required to queue events to report about the operator's actions, and to attach dangling events to their
# respective involved objects.
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get

# Permissions required to automatically restart (i.e. delete) pods when instrumenting replicasets that are not part of a
# higher order workload (e.g. a deployment, daemonset).
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list

# Permissions required to manage the Dash0 monitoring resource, its finalizers and status.
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0monitorings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

# Permissions required to manage the Dash0 monitoring resource, its finalizers and status.
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0monitorings/finalizers
  verbs:
  - update

# Permissions required to manage the Dash0 monitoring resource, its finalizers and status.
- apiGroups:
  - operator.dash0.com
  resources:
  - dash0monitorings/status
  verbs:
  - get
  - patch
  - update


# Permissions required to manage OTel collector resources.
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  # Note: apps.daemonsets are also listed further up together with the other workload types in the apps API group, with
  # fewer permissions. The declaration here extends that list of permissions to make sure we can also create and delete
  # the daemonsets for the OTel collector instances that the Dash0 operator manages.
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Permissions required due to the fact that the operator needs to create a dedicated service account/cluster role/
# cluster role binding for the OTel collector and give it a set of permissions; which it can only do if holds these
# permissions itself.
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dash0-operator.chartName" . }}-metrics-reader
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: metrics-role
    {{- include "dash0-operator.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dash0-operator.chartName" . }}-proxy-role
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: proxy-role
    {{- include "dash0-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
