apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dash0-operator.collectorResourceConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: collector-resources-config-map
    {{- include "dash0-operator.labels" . | nindent 4 }}

data:
  otelcolresources.yaml: |-
    collectorDaemonSetCollectorContainerResources:
      {{- toYaml .Values.operator.collectorDaemonSetCollectorContainerResources | nindent 6 }}
    collectorDaemonSetConfigurationReloaderContainerResources:
      {{- toYaml .Values.operator.collectorDaemonSetConfigurationReloaderContainerResources | nindent 6 }}
    collectorDaemonSetFileLogOffsetSynchContainerResources:
      {{- toYaml .Values.operator.collectorDaemonSetFileLogOffsetSynchContainerResources | nindent 6 }}

    collectorDeploymentCollectorContainerResources:
      {{- toYaml .Values.operator.collectorDeploymentCollectorContainerResources | nindent 6 }}
    collectorDeploymentConfigurationReloaderContainerResources:
      {{- toYaml .Values.operator.collectorDeploymentConfigurationReloaderContainerResources | nindent 6 }}