{{- if (and .Values.operator.gke.autopilot.enabled .Values.operator.gke.autopilot.deployAllowlistSynchronizer) }}
{{/*
This job needs its own separate ClusterRole, ClusterRoleBinding and ServiceAccount because all resources from the main
Helm chart have already been deleted by the time this runs.
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dash0-operator.postDeleteHookServiceAccountName" . }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dash0-operator.chartName" . }}-post-delete-role
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
rules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
  - apiGroups:
    - auto.gke.io
    resources:
    - allowlistsynchronizers
    verbs:
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "dash0-operator.chartName" . }}-post-delete-role-binding
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "dash0-operator.chartName" . }}-post-delete-role
subjects:
  - kind: ServiceAccount
    name: {{ template "dash0-operator.postDeleteHookServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dash0-operator.chartName" . }}-post-delete-remove-allowlist-synchronizer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: remove-allowlist-synchronizer
    {{- include "dash0-operator.labels" . | nindent 4 }}
    dash0.com/enable: "false"
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "hook-succeeded"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-post-delete-job-remove-allowlist-synchronizer
      labels:
        app.kubernetes.io/name: dash0-operator
        app.kubernetes.io/component: remove-allowlist-synchronizer
        app.kubernetes.io/instance: post-delete-hook
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        helm.sh/chart: {{ include "dash0-operator.chartNameWithVersion" . }}
        cloud.google.com/matching-allowlist: dash0-post-delete-remove-allowlist-synchronizer-v1.0.1
    spec:
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "dash0.com/enable"
                    operator: "NotIn"
                    values: ["false"]
                  - key: "kubernetes.io/os"
                    operator: "In"
                    values: ["linux"]
{{- if .Values.operator.tolerations }}
      tolerations:
        {{- toYaml .Values.operator.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.operator.managerPriorityClassName }}
      priorityClassName: {{ .Values.operator.managerPriorityClassName }}
{{- end }}
      containers:
        - name: remove-allowlist-synchronizer-job
          image: {{ include "dash0-operator.image" . | quote }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          command:
            - /manager
          args:
            - "--delete-allowlist-synchronizer"
          {{ include "dash0-operator.restrictiveContainerSecurityContext" dict | nindent 10 }}
          env:
            - name: GOMEMLIMIT
              value: {{ .Values.operator.managerContainerResources.gomemlimit }}
          resources:
            {{- unset (.Values.operator.managerContainerResources | mustDeepCopy) "gomemlimit" | toYaml | nindent 12 }}
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ template "dash0-operator.postDeleteHookServiceAccountName" . }}
      automountServiceAccountToken: true
  backoffLimit: 2
{{- end }}