{{- if .Values.operator.dash0Export.enabled }}
# If the Helm chart values have requested the automatic installation of a Dash0 operator configuration resource,
# we run a post-install hook to check whether that resource has been successfully created
# Thereby, helm install --wait ... will only terminate once that condition is reached.
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dash0-operator.chartName" . }}-post-install
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: installation-process
    {{- include "dash0-operator.labels" . | nindent 4 }}
    dash0.com/enable: "false"
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-post-install-job
      labels:
        app.kubernetes.io/name: dash0-operator
        app.kubernetes.io/component: readiness-check
        app.kubernetes.io/instance: post-install-hook
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        helm.sh/chart: {{ include "dash0-operator.chartNameWithVersion" . }}
        {{- if .Values.operator.gke.autopilot.enabled }}
        cloud.google.com/matching-allowlist: dash0-post-install-v1.0.0
        {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "dash0.com/enable"
                    operator: "NotIn"
                    values: ["false"]
                  - key: "kubernetes.io/os"
                    operator: "In"
                    values: ["linux"]
{{- if .Values.operator.tolerations }}
      tolerations:
        {{- toYaml .Values.operator.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.operator.managerPriorityClassName }}
      priorityClassName: {{ .Values.operator.managerPriorityClassName }}
{{- end }}
      restartPolicy: OnFailure
      containers:
        - name: post-install-job
          image: {{ include "dash0-operator.image" . | quote }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          command:
            - /manager
          args:
            - "--auto-operator-configuration-resource-available-check"
          {{ include "dash0-operator.restrictiveContainerSecurityContext" dict | nindent 10 }}
          resources:
            {{- toYaml .Values.operator.managerContainerResources | nindent 12 }}
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ template "dash0-operator.serviceAccountName" . }}
      automountServiceAccountToken: true
  backoffLimit: 2
  {{- end }}