apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dash0-operator.chartName" . }}-pre-delete
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dash0-operator
    app.kubernetes.io/component: uninstallation-process
    {{- include "dash0-operator.labels" . | nindent 4 }}
    dash0.com/enable: "false"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-pre-delete-job
      labels:
        app.kubernetes.io/name: dash0-operator
        app.kubernetes.io/component: uninstallation-process
        app.kubernetes.io/instance: pre-delete-hook
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        helm.sh/chart: {{ include "dash0-operator.chartNameWithVersion" . }}
        {{- if .Values.operator.gke.autopilot.enabled }}
        cloud.google.com/matching-allowlist: dash0-pre-delete-v1.0.0
        {{- end }}
    spec:
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "dash0.com/enable"
                    operator: "NotIn"
                    values: ["false"]
                  - key: "kubernetes.io/os"
                    operator: "In"
                    values: ["linux"]
{{- if .Values.operator.tolerations }}
      tolerations:
        {{- toYaml .Values.operator.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.operator.managerPriorityClassName }}
      priorityClassName: {{ .Values.operator.managerPriorityClassName }}
{{- end }}
      containers:
        - name: pre-delete-job
          image: {{ include "dash0-operator.image" . | quote }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          command:
            - /manager
          args:
            - "--uninstrument-all"
          {{ include "dash0-operator.restrictiveContainerSecurityContext" dict | nindent 10 }}
          resources:
            {{- toYaml .Values.operator.managerContainerResources | nindent 12 }}
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ template "dash0-operator.serviceAccountName" . }}
      automountServiceAccountToken: true
  backoffLimit: 2