apiVersion: v1
kind: Service
metadata:
  name: {{ include "dash0-operator.chartName" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    {{- include "dash0-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  {{- with .Values.operator.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: https
    port: {{ .Values.operator.metricsPort }}
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
