# SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

# This configuration is only used when running otlp-sink directly as a container via start.sh, not when
# running in Kubernetes via kubectl apply -f otlp-sink.yaml.
extensions:
  health_check:
    endpoint: 0.0.0.0:13133

exporters:
  debug:
    verbosity: detailed
  file/traces:
    path: /telemetry/traces.jsonl
    flush_interval: 100ms
  file/metrics:
    path: /telemetry/metrics.jsonl
    flush_interval: 100ms
  file/logs:
    path: /telemetry/logs.jsonl
    flush_interval: 100ms

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 64
      http:
        endpoint: 0.0.0.0:4318
        max_request_body_size: 20971520
service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - debug
        - file/traces
    metrics:
      receivers:
        - otlp
      exporters:
        - debug
        - file/metrics
    logs:
      receivers:
        - otlp
      exporters:
        - debug
        - file/logs
