apiVersion: v1
kind: Namespace
metadata:
  name: otlp-sink
  namespace: otlp-sink
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otlp-sink
  namespace: otlp-sink
data:
  config.yaml: |
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13100

    exporters:
      debug:
        verbosity: detailed
      file/traces:
        path: /telemetry/traces.jsonl
        flush_interval: 100ms
      file/metrics:
        path: /telemetry/metrics.jsonl
        flush_interval: 100ms
      file/logs:
        path: /telemetry/logs.jsonl
        flush_interval: 100ms

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers:
            - otlp
          exporters:
            - debug
            - file/traces
        metrics:
          receivers:
            - otlp
          exporters:
            - debug
            - file/metrics
        logs:
          receivers:
            - otlp
          exporters:
            - debug
            - file/logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otlp-sink
  namespace: otlp-sink
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/component: manager
    dash0.com/instrumented: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: otlp-sink
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: otlp-sink
    spec:
      containers:
      - name: otelcol
        image: otel/opentelemetry-collector-contrib:0.108.0
        imagePullPolicy: IfNotPresent
        args: ["--config=/etc/otelcol/config/config.yaml"]
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GOMEMLIMIT
          value: 400MiB
        ports:
        - name: otlp
          containerPort: 4317
          protocol: TCP
        - name: otlp-http
          containerPort: 4318
          protocol: TCP
        volumeMounts:
        - name: otelcol-config
          mountPath: /etc/otelcol/config
          readOnly: true
        - name: telemetry-file-export
          mountPath: /telemetry
          readOnly: false
        livenessProbe:
          httpGet:
            path: /
            port: 13100
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 13100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 500Mi
          requests:
            cpu: 10m
            memory: 64Mi
            ephemeral-storage: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: otelcol-config
        configMap:
          name: otlp-sink
          items:
          - key: config.yaml
            path: config.yaml
      - name: telemetry-file-export
        hostPath:
          type: DirectoryOrCreate
          # If you change this line below, you need to update the e2e helpers
          # and update the string replacement to the actual folder
          path: /tmp/telemetry
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: otlp-sink
  namespace: otlp-sink
  labels:
    app.kubernetes.io/name: otlp-sink
    app.kubernetes.io/component: service
spec:
  ports:
  - name: otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app.kubernetes.io/instance: otlp-sink