//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/dash0hq/dash0-operator/api/operator/common"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectNamespaceLabelsAndAnnotations) DeepCopyInto(out *CollectNamespaceLabelsAndAnnotations) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectNamespaceLabelsAndAnnotations.
func (in *CollectNamespaceLabelsAndAnnotations) DeepCopy() *CollectNamespaceLabelsAndAnnotations {
	if in == nil {
		return nil
	}
	out := new(CollectNamespaceLabelsAndAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectPodLabelsAndAnnotations) DeepCopyInto(out *CollectPodLabelsAndAnnotations) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectPodLabelsAndAnnotations.
func (in *CollectPodLabelsAndAnnotations) DeepCopy() *CollectPodLabelsAndAnnotations {
	if in == nil {
		return nil
	}
	out := new(CollectPodLabelsAndAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0Monitoring) DeepCopyInto(out *Dash0Monitoring) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0Monitoring.
func (in *Dash0Monitoring) DeepCopy() *Dash0Monitoring {
	if in == nil {
		return nil
	}
	out := new(Dash0Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0Monitoring) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0MonitoringList) DeepCopyInto(out *Dash0MonitoringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0Monitoring, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0MonitoringList.
func (in *Dash0MonitoringList) DeepCopy() *Dash0MonitoringList {
	if in == nil {
		return nil
	}
	out := new(Dash0MonitoringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0MonitoringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0MonitoringSpec) DeepCopyInto(out *Dash0MonitoringSpec) {
	*out = *in
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(common.Export)
		(*in).DeepCopyInto(*out)
	}
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]common.Export, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LogCollection.DeepCopyInto(&out.LogCollection)
	in.PrometheusScraping.DeepCopyInto(&out.PrometheusScraping)
	if in.PrometheusScrapingEnabled != nil {
		in, out := &in.PrometheusScrapingEnabled, &out.PrometheusScrapingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(common.Filter)
		(*in).DeepCopyInto(*out)
	}
	if in.Transform != nil {
		in, out := &in.Transform, &out.Transform
		*out = new(common.Transform)
		(*in).DeepCopyInto(*out)
	}
	if in.NormalizedTransformSpec != nil {
		in, out := &in.NormalizedTransformSpec, &out.NormalizedTransformSpec
		*out = new(common.NormalizedTransformSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SynchronizePersesDashboards != nil {
		in, out := &in.SynchronizePersesDashboards, &out.SynchronizePersesDashboards
		*out = new(bool)
		**out = **in
	}
	if in.SynchronizePrometheusRules != nil {
		in, out := &in.SynchronizePrometheusRules, &out.SynchronizePrometheusRules
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0MonitoringSpec.
func (in *Dash0MonitoringSpec) DeepCopy() *Dash0MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0MonitoringStatus) DeepCopyInto(out *Dash0MonitoringStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PersesDashboardSynchronizationResults != nil {
		in, out := &in.PersesDashboardSynchronizationResults, &out.PersesDashboardSynchronizationResults
		*out = make(map[string]common.PersesDashboardSynchronizationResults, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PrometheusRuleSynchronizationResults != nil {
		in, out := &in.PrometheusRuleSynchronizationResults, &out.PrometheusRuleSynchronizationResults
		*out = make(map[string]common.PrometheusRuleSynchronizationResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0MonitoringStatus.
func (in *Dash0MonitoringStatus) DeepCopy() *Dash0MonitoringStatus {
	if in == nil {
		return nil
	}
	out := new(Dash0MonitoringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0OperatorConfiguration) DeepCopyInto(out *Dash0OperatorConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0OperatorConfiguration.
func (in *Dash0OperatorConfiguration) DeepCopy() *Dash0OperatorConfiguration {
	if in == nil {
		return nil
	}
	out := new(Dash0OperatorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0OperatorConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0OperatorConfigurationList) DeepCopyInto(out *Dash0OperatorConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0OperatorConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0OperatorConfigurationList.
func (in *Dash0OperatorConfigurationList) DeepCopy() *Dash0OperatorConfigurationList {
	if in == nil {
		return nil
	}
	out := new(Dash0OperatorConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0OperatorConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0OperatorConfigurationSpec) DeepCopyInto(out *Dash0OperatorConfigurationSpec) {
	*out = *in
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(common.Export)
		(*in).DeepCopyInto(*out)
	}
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]common.Export, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.SelfMonitoring.DeepCopyInto(&out.SelfMonitoring)
	in.KubernetesInfrastructureMetricsCollection.DeepCopyInto(&out.KubernetesInfrastructureMetricsCollection)
	if in.KubernetesInfrastructureMetricsCollectionEnabled != nil {
		in, out := &in.KubernetesInfrastructureMetricsCollectionEnabled, &out.KubernetesInfrastructureMetricsCollectionEnabled
		*out = new(bool)
		**out = **in
	}
	in.CollectPodLabelsAndAnnotations.DeepCopyInto(&out.CollectPodLabelsAndAnnotations)
	in.CollectNamespaceLabelsAndAnnotations.DeepCopyInto(&out.CollectNamespaceLabelsAndAnnotations)
	in.PrometheusCrdSupport.DeepCopyInto(&out.PrometheusCrdSupport)
	in.TelemetryCollection.DeepCopyInto(&out.TelemetryCollection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0OperatorConfigurationSpec.
func (in *Dash0OperatorConfigurationSpec) DeepCopy() *Dash0OperatorConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0OperatorConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0OperatorConfigurationStatus) DeepCopyInto(out *Dash0OperatorConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0OperatorConfigurationStatus.
func (in *Dash0OperatorConfigurationStatus) DeepCopy() *Dash0OperatorConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(Dash0OperatorConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheck) DeepCopyInto(out *Dash0SyntheticCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheck.
func (in *Dash0SyntheticCheck) DeepCopy() *Dash0SyntheticCheck {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0SyntheticCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckAssertion) DeepCopyInto(out *Dash0SyntheticCheckAssertion) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckAssertion.
func (in *Dash0SyntheticCheckAssertion) DeepCopy() *Dash0SyntheticCheckAssertion {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckAssertionSpec) DeepCopyInto(out *Dash0SyntheticCheckAssertionSpec) {
	*out = *in
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.JSONPath != nil {
		in, out := &in.JSONPath, &out.JSONPath
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckAssertionSpec.
func (in *Dash0SyntheticCheckAssertionSpec) DeepCopy() *Dash0SyntheticCheckAssertionSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckAssertionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckDisplay) DeepCopyInto(out *Dash0SyntheticCheckDisplay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckDisplay.
func (in *Dash0SyntheticCheckDisplay) DeepCopy() *Dash0SyntheticCheckDisplay {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPAssertions) DeepCopyInto(out *Dash0SyntheticCheckHTTPAssertions) {
	*out = *in
	if in.CriticalAssertions != nil {
		in, out := &in.CriticalAssertions, &out.CriticalAssertions
		*out = make([]Dash0SyntheticCheckAssertion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DegradedAssertions != nil {
		in, out := &in.DegradedAssertions, &out.DegradedAssertions
		*out = make([]Dash0SyntheticCheckAssertion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPAssertions.
func (in *Dash0SyntheticCheckHTTPAssertions) DeepCopy() *Dash0SyntheticCheckHTTPAssertions {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPAssertions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPBasicAuthentication) DeepCopyInto(out *Dash0SyntheticCheckHTTPBasicAuthentication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPBasicAuthentication.
func (in *Dash0SyntheticCheckHTTPBasicAuthentication) DeepCopy() *Dash0SyntheticCheckHTTPBasicAuthentication {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPBasicAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPBody) DeepCopyInto(out *Dash0SyntheticCheckHTTPBody) {
	*out = *in
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPBody.
func (in *Dash0SyntheticCheckHTTPBody) DeepCopy() *Dash0SyntheticCheckHTTPBody {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPBodySpec) DeepCopyInto(out *Dash0SyntheticCheckHTTPBodySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPBodySpec.
func (in *Dash0SyntheticCheckHTTPBodySpec) DeepCopy() *Dash0SyntheticCheckHTTPBodySpec {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPBodySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPHeader) DeepCopyInto(out *Dash0SyntheticCheckHTTPHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPHeader.
func (in *Dash0SyntheticCheckHTTPHeader) DeepCopy() *Dash0SyntheticCheckHTTPHeader {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPPluginSpec) DeepCopyInto(out *Dash0SyntheticCheckHTTPPluginSpec) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	in.Assertions.DeepCopyInto(&out.Assertions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPPluginSpec.
func (in *Dash0SyntheticCheckHTTPPluginSpec) DeepCopy() *Dash0SyntheticCheckHTTPPluginSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPQueryParameter) DeepCopyInto(out *Dash0SyntheticCheckHTTPQueryParameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPQueryParameter.
func (in *Dash0SyntheticCheckHTTPQueryParameter) DeepCopy() *Dash0SyntheticCheckHTTPQueryParameter {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPQueryParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPRequest) DeepCopyInto(out *Dash0SyntheticCheckHTTPRequest) {
	*out = *in
	out.TLS = in.TLS
	out.Tracing = in.Tracing
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]Dash0SyntheticCheckHTTPHeader, len(*in))
		copy(*out, *in)
	}
	if in.QueryParameters != nil {
		in, out := &in.QueryParameters, &out.QueryParameters
		*out = make([]Dash0SyntheticCheckHTTPQueryParameter, len(*in))
		copy(*out, *in)
	}
	if in.BasicAuthentication != nil {
		in, out := &in.BasicAuthentication, &out.BasicAuthentication
		*out = new(Dash0SyntheticCheckHTTPBasicAuthentication)
		**out = **in
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(Dash0SyntheticCheckHTTPBody)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPRequest.
func (in *Dash0SyntheticCheckHTTPRequest) DeepCopy() *Dash0SyntheticCheckHTTPRequest {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPTLS) DeepCopyInto(out *Dash0SyntheticCheckHTTPTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPTLS.
func (in *Dash0SyntheticCheckHTTPTLS) DeepCopy() *Dash0SyntheticCheckHTTPTLS {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckHTTPTracing) DeepCopyInto(out *Dash0SyntheticCheckHTTPTracing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckHTTPTracing.
func (in *Dash0SyntheticCheckHTTPTracing) DeepCopy() *Dash0SyntheticCheckHTTPTracing {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckHTTPTracing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckList) DeepCopyInto(out *Dash0SyntheticCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0SyntheticCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckList.
func (in *Dash0SyntheticCheckList) DeepCopy() *Dash0SyntheticCheckList {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0SyntheticCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckNotifications) DeepCopyInto(out *Dash0SyntheticCheckNotifications) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]NotificationChannelID, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckNotifications.
func (in *Dash0SyntheticCheckNotifications) DeepCopy() *Dash0SyntheticCheckNotifications {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckNotifications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckPlugin) DeepCopyInto(out *Dash0SyntheticCheckPlugin) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckPlugin.
func (in *Dash0SyntheticCheckPlugin) DeepCopy() *Dash0SyntheticCheckPlugin {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckRetries) DeepCopyInto(out *Dash0SyntheticCheckRetries) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckRetries.
func (in *Dash0SyntheticCheckRetries) DeepCopy() *Dash0SyntheticCheckRetries {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckRetries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckRetriesSpec) DeepCopyInto(out *Dash0SyntheticCheckRetriesSpec) {
	*out = *in
	if in.Attempts != nil {
		in, out := &in.Attempts, &out.Attempts
		*out = new(int)
		**out = **in
	}
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(string)
		**out = **in
	}
	if in.MaximumDelay != nil {
		in, out := &in.MaximumDelay, &out.MaximumDelay
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckRetriesSpec.
func (in *Dash0SyntheticCheckRetriesSpec) DeepCopy() *Dash0SyntheticCheckRetriesSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckRetriesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckSchedule) DeepCopyInto(out *Dash0SyntheticCheckSchedule) {
	*out = *in
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckSchedule.
func (in *Dash0SyntheticCheckSchedule) DeepCopy() *Dash0SyntheticCheckSchedule {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckSpec) DeepCopyInto(out *Dash0SyntheticCheckSpec) {
	*out = *in
	out.Display = in.Display
	in.Plugin.DeepCopyInto(&out.Plugin)
	in.Schedule.DeepCopyInto(&out.Schedule)
	in.Retries.DeepCopyInto(&out.Retries)
	in.Notifications.DeepCopyInto(&out.Notifications)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckSpec.
func (in *Dash0SyntheticCheckSpec) DeepCopy() *Dash0SyntheticCheckSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckStatus) DeepCopyInto(out *Dash0SyntheticCheckStatus) {
	*out = *in
	in.SynchronizedAt.DeepCopyInto(&out.SynchronizedAt)
	if in.ValidationIssues != nil {
		in, out := &in.ValidationIssues, &out.ValidationIssues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SynchronizationResults != nil {
		in, out := &in.SynchronizationResults, &out.SynchronizationResults
		*out = make([]Dash0SyntheticCheckSynchronizationResultPerEndpointAndDataset, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckStatus.
func (in *Dash0SyntheticCheckStatus) DeepCopy() *Dash0SyntheticCheckStatus {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SyntheticCheckSynchronizationResultPerEndpointAndDataset) DeepCopyInto(out *Dash0SyntheticCheckSynchronizationResultPerEndpointAndDataset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SyntheticCheckSynchronizationResultPerEndpointAndDataset.
func (in *Dash0SyntheticCheckSynchronizationResultPerEndpointAndDataset) DeepCopy() *Dash0SyntheticCheckSynchronizationResultPerEndpointAndDataset {
	if in == nil {
		return nil
	}
	out := new(Dash0SyntheticCheckSynchronizationResultPerEndpointAndDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0View) DeepCopyInto(out *Dash0View) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0View.
func (in *Dash0View) DeepCopy() *Dash0View {
	if in == nil {
		return nil
	}
	out := new(Dash0View)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0View) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewDisplay) DeepCopyInto(out *Dash0ViewDisplay) {
	*out = *in
	if in.Folder != nil {
		in, out := &in.Folder, &out.Folder
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewDisplay.
func (in *Dash0ViewDisplay) DeepCopy() *Dash0ViewDisplay {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewFilter) DeepCopyInto(out *Dash0ViewFilter) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewFilter.
func (in *Dash0ViewFilter) DeepCopy() *Dash0ViewFilter {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewList) DeepCopyInto(out *Dash0ViewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0View, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewList.
func (in *Dash0ViewList) DeepCopy() *Dash0ViewList {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0ViewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewPermission) DeepCopyInto(out *Dash0ViewPermission) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]Dash0ViewAction, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewPermission.
func (in *Dash0ViewPermission) DeepCopy() *Dash0ViewPermission {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewSpec) DeepCopyInto(out *Dash0ViewSpec) {
	*out = *in
	in.Display.DeepCopyInto(&out.Display)
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]Dash0ViewPermission, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]Dash0ViewFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImplicitFilter != nil {
		in, out := &in.ImplicitFilter, &out.ImplicitFilter
		*out = make([]Dash0ViewFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(Dash0ViewTable)
		(*in).DeepCopyInto(*out)
	}
	if in.Visualizations != nil {
		in, out := &in.Visualizations, &out.Visualizations
		*out = make([]Dash0ViewVisualization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewSpec.
func (in *Dash0ViewSpec) DeepCopy() *Dash0ViewSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewStatus) DeepCopyInto(out *Dash0ViewStatus) {
	*out = *in
	in.SynchronizedAt.DeepCopyInto(&out.SynchronizedAt)
	if in.ValidationIssues != nil {
		in, out := &in.ValidationIssues, &out.ValidationIssues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SynchronizationResults != nil {
		in, out := &in.SynchronizationResults, &out.SynchronizationResults
		*out = make([]Dash0ViewSynchronizationResultPerEndpointAndDataset, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewStatus.
func (in *Dash0ViewStatus) DeepCopy() *Dash0ViewStatus {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewSynchronizationResultPerEndpointAndDataset) DeepCopyInto(out *Dash0ViewSynchronizationResultPerEndpointAndDataset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewSynchronizationResultPerEndpointAndDataset.
func (in *Dash0ViewSynchronizationResultPerEndpointAndDataset) DeepCopy() *Dash0ViewSynchronizationResultPerEndpointAndDataset {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewSynchronizationResultPerEndpointAndDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewTable) DeepCopyInto(out *Dash0ViewTable) {
	*out = *in
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]Dash0ViewTableColumn, len(*in))
		copy(*out, *in)
	}
	if in.Sort != nil {
		in, out := &in.Sort, &out.Sort
		*out = make([]Dash0ViewTableSort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewTable.
func (in *Dash0ViewTable) DeepCopy() *Dash0ViewTable {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewTableColumn) DeepCopyInto(out *Dash0ViewTableColumn) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewTableColumn.
func (in *Dash0ViewTableColumn) DeepCopy() *Dash0ViewTableColumn {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewTableColumn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewTableSort) DeepCopyInto(out *Dash0ViewTableSort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewTableSort.
func (in *Dash0ViewTableSort) DeepCopy() *Dash0ViewTableSort {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewTableSort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0ViewVisualization) DeepCopyInto(out *Dash0ViewVisualization) {
	*out = *in
	if in.Renderers != nil {
		in, out := &in.Renderers, &out.Renderers
		*out = make([]Dash0ViewRenderer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0ViewVisualization.
func (in *Dash0ViewVisualization) DeepCopy() *Dash0ViewVisualization {
	if in == nil {
		return nil
	}
	out := new(Dash0ViewVisualization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesInfrastructureMetricsCollection) DeepCopyInto(out *KubernetesInfrastructureMetricsCollection) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesInfrastructureMetricsCollection.
func (in *KubernetesInfrastructureMetricsCollection) DeepCopy() *KubernetesInfrastructureMetricsCollection {
	if in == nil {
		return nil
	}
	out := new(KubernetesInfrastructureMetricsCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusCrdSupport) DeepCopyInto(out *PrometheusCrdSupport) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusCrdSupport.
func (in *PrometheusCrdSupport) DeepCopy() *PrometheusCrdSupport {
	if in == nil {
		return nil
	}
	out := new(PrometheusCrdSupport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfMonitoring) DeepCopyInto(out *SelfMonitoring) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfMonitoring.
func (in *SelfMonitoring) DeepCopy() *SelfMonitoring {
	if in == nil {
		return nil
	}
	out := new(SelfMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryCollection) DeepCopyInto(out *TelemetryCollection) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryCollection.
func (in *TelemetryCollection) DeepCopy() *TelemetryCollection {
	if in == nil {
		return nil
	}
	out := new(TelemetryCollection)
	in.DeepCopyInto(out)
	return out
}
