//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2024 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0) DeepCopyInto(out *Dash0) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0.
func (in *Dash0) DeepCopy() *Dash0 {
	if in == nil {
		return nil
	}
	out := new(Dash0)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0List) DeepCopyInto(out *Dash0List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0List.
func (in *Dash0List) DeepCopy() *Dash0List {
	if in == nil {
		return nil
	}
	out := new(Dash0List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0Spec) DeepCopyInto(out *Dash0Spec) {
	*out = *in
	if in.InstrumentWorkloads != nil {
		in, out := &in.InstrumentWorkloads, &out.InstrumentWorkloads
		*out = new(bool)
		**out = **in
	}
	if in.InstrumentExistingWorkloads != nil {
		in, out := &in.InstrumentExistingWorkloads, &out.InstrumentExistingWorkloads
		*out = new(bool)
		**out = **in
	}
	if in.InstrumentNewWorkloads != nil {
		in, out := &in.InstrumentNewWorkloads, &out.InstrumentNewWorkloads
		*out = new(bool)
		**out = **in
	}
	if in.UninstrumentWorkloadsOnDelete != nil {
		in, out := &in.UninstrumentWorkloadsOnDelete, &out.UninstrumentWorkloadsOnDelete
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0Spec.
func (in *Dash0Spec) DeepCopy() *Dash0Spec {
	if in == nil {
		return nil
	}
	out := new(Dash0Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0Status) DeepCopyInto(out *Dash0Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0Status.
func (in *Dash0Status) DeepCopy() *Dash0Status {
	if in == nil {
		return nil
	}
	out := new(Dash0Status)
	in.DeepCopyInto(out)
	return out
}
