//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SpamFilter) DeepCopyInto(out *Dash0SpamFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SpamFilter.
func (in *Dash0SpamFilter) DeepCopy() *Dash0SpamFilter {
	if in == nil {
		return nil
	}
	out := new(Dash0SpamFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0SpamFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SpamFilterCondition) DeepCopyInto(out *Dash0SpamFilterCondition) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SpamFilterCondition.
func (in *Dash0SpamFilterCondition) DeepCopy() *Dash0SpamFilterCondition {
	if in == nil {
		return nil
	}
	out := new(Dash0SpamFilterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SpamFilterList) DeepCopyInto(out *Dash0SpamFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0SpamFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SpamFilterList.
func (in *Dash0SpamFilterList) DeepCopy() *Dash0SpamFilterList {
	if in == nil {
		return nil
	}
	out := new(Dash0SpamFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0SpamFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SpamFilterSpec) DeepCopyInto(out *Dash0SpamFilterSpec) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]Dash0SpamFilterCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SpamFilterSpec.
func (in *Dash0SpamFilterSpec) DeepCopy() *Dash0SpamFilterSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0SpamFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SpamFilterStatus) DeepCopyInto(out *Dash0SpamFilterStatus) {
	*out = *in
	in.SynchronizedAt.DeepCopyInto(&out.SynchronizedAt)
	if in.ValidationIssues != nil {
		in, out := &in.ValidationIssues, &out.ValidationIssues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SynchronizationResults != nil {
		in, out := &in.SynchronizationResults, &out.SynchronizationResults
		*out = make([]Dash0SpamFilterSynchronizationResultPerEndpointAndDataset, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SpamFilterStatus.
func (in *Dash0SpamFilterStatus) DeepCopy() *Dash0SpamFilterStatus {
	if in == nil {
		return nil
	}
	out := new(Dash0SpamFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0SpamFilterSynchronizationResultPerEndpointAndDataset) DeepCopyInto(out *Dash0SpamFilterSynchronizationResultPerEndpointAndDataset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0SpamFilterSynchronizationResultPerEndpointAndDataset.
func (in *Dash0SpamFilterSynchronizationResultPerEndpointAndDataset) DeepCopy() *Dash0SpamFilterSynchronizationResultPerEndpointAndDataset {
	if in == nil {
		return nil
	}
	out := new(Dash0SpamFilterSynchronizationResultPerEndpointAndDataset)
	in.DeepCopyInto(out)
	return out
}
