# SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

ARG base_image="golang:1.25.5-trixie"
FROM --platform=${BUILDPLATFORM} ${base_image}

WORKDIR /workspace

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY main.go .

ARG TARGETOS
ARG TARGETARCH

RUN GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -v -buildmode=pie -ldflags '-s -w' -o noenviron .

