apiVersion: v2
version: 1.0.0
# SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0
name: ruby-sinatra-demo-app
description: Sinatra demo app for the Dash0 Ruby auto-instrumentation demo
