# SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

image:
  repository: dash0-operator-ruby-sinatra-demo-app
  tag: latest
  pullPolicy: IfNotPresent

port: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
