# SPDX-FileCopyrightText: Copyright 2024 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: dash0-operator-nodejs-20-express-test-daemonset-service
spec:
  selector:
    app: dash0-operator-nodejs-20-express-test-daemonset-app
  ports:
    - port: 1206
      targetPort: 1206
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dash0-operator-nodejs-20-express-test-daemonset
  labels:
    app: dash0-operator-nodejs-20-express-test-daemonset-app
    dash0.com/enable: "false"
    # Used in the end-to-end test "Dash0 Operator ... with a custom auto-instrumentation label selector - should
    # instrument workloads that match the label selector".
    instrument-with-dash0: "yes"
spec:
  selector:
    matchLabels:
      app: dash0-operator-nodejs-20-express-test-daemonset-app
  template:
    metadata:
      labels:
        app: dash0-operator-nodejs-20-express-test-daemonset-app
        app.kubernetes.io/name: "test-daemonset"
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/part-of: "dash0-operator-test"
        app.kubernetes.io/instance: "express"
        test.label/key: "label-value"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1206"
        test.annotation/key: "annotation value"
    spec:
      containers:
        - name: dash0-operator-nodejs-20-express-test-daemonset-app
          image: "dash0-operator-nodejs-20-express-test-app:latest"
          env:
            - name: PORT
              value: "1206"
          ports:
            - containerPort: 1206
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
              ephemeral-storage: 500Mi
            requests:
              cpu: 100m
              memory: 64Mi
              ephemeral-storage: 500Mi
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: 1206
            initialDelaySeconds: 1
            periodSeconds: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash0-operator-nodejs-20-express-test-daemonset-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /daemonset/node.js(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dash0-operator-nodejs-20-express-test-daemonset-service
            port:
              number: 1206
