# SPDX-FileCopyrightText: Copyright 2024 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: dash0-operator-nodejs-20-express-test-job
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "test-job"
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/part-of: "dash0-operator-test"
        app.kubernetes.io/instance: "express"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1208"
    spec:
      restartPolicy: Never
      containers:
        - name: dash0-operator-nodejs-20-express-test-job-app
          image: "dash0-operator-nodejs-20-express-test-app:latest"
          env:
            - name: PORT
              value: "1208"
            - name: DASH0_DEBUG
              value: "true"
            - name: TRIGGER_SELF_AND_EXIT
              value: "true"
            #- name: OTEL_LOG_LEVEL
            #  value: "debug"
          ports:
            - containerPort: 1208
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
              ephemeral-storage: 500Mi
            requests:
              cpu: 100m
              memory: 64Mi
              ephemeral-storage: 500Mi
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: 1208
            initialDelaySeconds: 1
            periodSeconds: 1
