# SPDX-FileCopyrightText: Copyright 2024 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: dash0-operator-nodejs-20-express-test-pod-service
spec:
  selector:
    app: dash0-operator-nodejs-20-express-test-pod-app
  ports:
    - port: 1211
      targetPort: 1211
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: dash0-operator-nodejs-20-express-test-pod
  labels:
    app: dash0-operator-nodejs-20-express-test-pod-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "1211"
spec:
  containers:
    - name: dash0-operator-nodejs-20-express-test-pod-app
      image: "dash0-operator-nodejs-20-express-test-app:latest"
      env:
        - name: PORT
          value: "1211"
        - name: DASH0_DEBUG
          value: "true"
      ports:
        - containerPort: 1211
      imagePullPolicy: Never
      readinessProbe:
        httpGet:
          path: /ready
          port: 1211
        initialDelaySeconds: 1
        periodSeconds: 1