# SPDX-FileCopyrightText: Copyright 2024 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: dash0-operator-nodejs-20-express-test-statefulset-service
spec:
  selector:
    app: dash0-operator-nodejs-20-express-test-statefulset-app
  ports:
    - port: 1210
      targetPort: 1210
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dash0-operator-nodejs-20-express-test-statefulset
spec:
  selector:
    matchLabels:
      app: dash0-operator-nodejs-20-express-test-statefulset-app
  serviceName: "dash0-operator-nodejs-20-express-test-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: dash0-operator-nodejs-20-express-test-statefulset-app
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: dash0-operator-nodejs-20-express-test-statefulset-app
          image: "dash0-operator-nodejs-20-express-test-app:latest"
          env:
            - name: PORT
              value: "1210"
            - name: DASH0_DEBUG
              value: "true"
          ports:
            - containerPort: 1210
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: 1210
            initialDelaySeconds: 1
            periodSeconds: 1