apiVersion: v1
kind: PersistentVolume
metadata:
  name:  test-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 200Mi
  hostPath:
    path: /test-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-volume
  namespace: test-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
