apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: docker-storage-class
provisioner: docker.io/hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-volume
  namespace: test-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: docker-storage-class
