apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: docker-storage-class
provisioner: docker.io/hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: offset-storage-claim
  namespace: operator-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: docker-storage-class
