# SPDX-FileCopyrightText: Copyright 2024 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

ARG base_image="node:22.15.0-bookworm-slim"
FROM ${base_image}

ARG injector_binary
RUN if [ -z "$injector_binary" ]; then \
      echo "Error: build argument injector_binary is required but not set."; \
      exit 1; \
    fi

ARG noenviron_binary
RUN if [ -z "$noenviron_binary" ]; then \
      echo "Error: build argument noenviron_binary is required but not set."; \
      exit 1; \
    fi

WORKDIR /usr/src/dash0/injector/

COPY app app
RUN mkdir no_environ_symbol
COPY no_environ_symbol/$noenviron_binary no_environ_symbol/noenviron
COPY scripts/run-tests-within-container.sh scripts/
COPY scripts/*.tests scripts/

RUN echo ${injector_binary}

COPY bin/${injector_binary} /dash0-init-container/injector/dash0_injector.so

ARG arch_under_test=no_value
RUN test ${arch_under_test} != "no_value"
ENV ARCH_UNDER_TEST=${arch_under_test}
ARG libc_under_test=no_value
RUN test ${libc_under_test} != "no_value"
ENV LIBC_UNDER_TEST=${libc_under_test}

USER node
CMD ["scripts/run-tests-within-container.sh"]

