apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: docker-storage-class
provisioner: docker.io/hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # To inspect the volume content and permissions:
  #   docker run -it --rm --privileged --pid=host justincormack/nsenter1
  #   cd /var/lib/k8s-pvs/offset-storage-claim
  name: offset-storage-claim
  namespace: operator-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: docker-storage-class
