apiVersion: v1
kind: PersistentVolume
metadata:
  name: filelogreceiver-offsets
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 50Mi
  hostPath:
    path: /offset-storage/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: offset-storage-claim
  namespace: operator-namespace
spec:
  volumeName: filelogreceiver-offsets
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
