apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: offset-storage-claim
  namespace: operator-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      # storage size is required but will be ignored with EFS
      storage: 1Gi
