# SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: dash0-operator-python-flask-test-daemonset-service
spec:
  selector:
    app: dash0-operator-python-flask-test-daemonset-app
  ports:
    - port: 1506
      targetPort: 1506
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dash0-operator-python-flask-test-daemonset
  labels:
    app: dash0-operator-python-flask-test-daemonset-app
spec:
  selector:
    matchLabels:
      app: dash0-operator-python-flask-test-daemonset-app
  template:
    metadata:
      labels:
        app: dash0-operator-python-flask-test-daemonset-app
        test.label/key: "label-value"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1506"
        test.annotation/key: "annotation value"
    spec:
      containers:
        - name: dash0-operator-python-flask-test-daemonset-app
          image: "dash0-operator-python-flask-test-app:latest"
          env:
            - name: PORT
              value: "1506"
          ports:
            - containerPort: 1506
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 500Mi
            requests:
              cpu: 200m
              memory: 128Mi
              ephemeral-storage: 500Mi
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: 1506
            initialDelaySeconds: 1
            periodSeconds: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash0-operator-python-flask-test-daemonset-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /daemonset(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dash0-operator-python-flask-test-daemonset-service
            port:
              number: 1506
