# SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: dash0-operator-python-flask-test-pod-service
spec:
  selector:
    app: dash0-operator-python-flask-test-pod-app
  ports:
    - port: 1511
      targetPort: 1511
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: dash0-operator-python-flask-test-pod
  labels:
    app: dash0-operator-python-flask-test-pod-app
    test.label/key: "label-value"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "1511"
    test.annotation/key: "annotation value"
spec:
  containers:
    - name: dash0-operator-python-flask-test-pod-app
      image: "dash0-operator-python-flask-test-app:latest"
      env:
        - name: PORT
          value: "1511"
      ports:
        - containerPort: 1511
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
          ephemeral-storage: 500Mi
        requests:
          cpu: 200m
          memory: 128Mi
          ephemeral-storage: 500Mi
      imagePullPolicy: Never
      readinessProbe:
        httpGet:
          path: /ready
          port: 1511
        initialDelaySeconds: 1
        periodSeconds: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash0-operator-python-flask-test-pod-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /pod/python(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dash0-operator-python-flask-test-pod-service
            port:
              number: 1511
