# SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: dash0-operator-python-flask-test-statefulset-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  selector:
    app: dash0-operator-python-flask-test-statefulset-app
  ports:
    - port: 1510
      targetPort: 1510
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dash0-operator-python-flask-test-statefulset
spec:
  selector:
    matchLabels:
      app: dash0-operator-python-flask-test-statefulset-app
  serviceName: "dash0-operator-python-flask-test-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: dash0-operator-python-flask-test-statefulset-app
        test.label/key: "label-value"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1510"
        test.annotation/key: "annotation value"
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: dash0-operator-python-flask-test-statefulset-app
          image: "dash0-operator-python-flask-test-app:latest"
          env:
            - name: PORT
              value: "1510"
          ports:
            - containerPort: 1510
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 500Mi
            requests:
              cpu: 200m
              memory: 128Mi
              ephemeral-storage: 500Mi
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: 1510
            initialDelaySeconds: 1
            periodSeconds: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash0-operator-python-flask-test-statefulset-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /statefulset/python(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dash0-operator-python-flask-test-statefulset-service
            port:
              number: 1510
