//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/dash0hq/dash0-operator/api/operator/common"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllQuietConfig) DeepCopyInto(out *AllQuietConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllQuietConfig.
func (in *AllQuietConfig) DeepCopy() *AllQuietConfig {
	if in == nil {
		return nil
	}
	out := new(AllQuietConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0Monitoring) DeepCopyInto(out *Dash0Monitoring) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0Monitoring.
func (in *Dash0Monitoring) DeepCopy() *Dash0Monitoring {
	if in == nil {
		return nil
	}
	out := new(Dash0Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0Monitoring) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0MonitoringList) DeepCopyInto(out *Dash0MonitoringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0Monitoring, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0MonitoringList.
func (in *Dash0MonitoringList) DeepCopy() *Dash0MonitoringList {
	if in == nil {
		return nil
	}
	out := new(Dash0MonitoringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0MonitoringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0MonitoringSpec) DeepCopyInto(out *Dash0MonitoringSpec) {
	*out = *in
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(common.Export)
		(*in).DeepCopyInto(*out)
	}
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]common.Export, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.InstrumentWorkloads.DeepCopyInto(&out.InstrumentWorkloads)
	in.LogCollection.DeepCopyInto(&out.LogCollection)
	in.EventCollection.DeepCopyInto(&out.EventCollection)
	in.PrometheusScraping.DeepCopyInto(&out.PrometheusScraping)
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(common.Filter)
		(*in).DeepCopyInto(*out)
	}
	if in.Transform != nil {
		in, out := &in.Transform, &out.Transform
		*out = new(common.Transform)
		(*in).DeepCopyInto(*out)
	}
	if in.NormalizedTransformSpec != nil {
		in, out := &in.NormalizedTransformSpec, &out.NormalizedTransformSpec
		*out = new(common.NormalizedTransformSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SynchronizePersesDashboards != nil {
		in, out := &in.SynchronizePersesDashboards, &out.SynchronizePersesDashboards
		*out = new(bool)
		**out = **in
	}
	if in.SynchronizePrometheusRules != nil {
		in, out := &in.SynchronizePrometheusRules, &out.SynchronizePrometheusRules
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0MonitoringSpec.
func (in *Dash0MonitoringSpec) DeepCopy() *Dash0MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0MonitoringStatus) DeepCopyInto(out *Dash0MonitoringStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PreviousInstrumentWorkloads.DeepCopyInto(&out.PreviousInstrumentWorkloads)
	in.PreviousLogCollection.DeepCopyInto(&out.PreviousLogCollection)
	if in.PersesDashboardSynchronizationResults != nil {
		in, out := &in.PersesDashboardSynchronizationResults, &out.PersesDashboardSynchronizationResults
		*out = make(map[string]common.PersesDashboardSynchronizationResults, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PrometheusRuleSynchronizationResults != nil {
		in, out := &in.PrometheusRuleSynchronizationResults, &out.PrometheusRuleSynchronizationResults
		*out = make(map[string]common.PrometheusRuleSynchronizationResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0MonitoringStatus.
func (in *Dash0MonitoringStatus) DeepCopy() *Dash0MonitoringStatus {
	if in == nil {
		return nil
	}
	out := new(Dash0MonitoringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0NotificationChannel) DeepCopyInto(out *Dash0NotificationChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0NotificationChannel.
func (in *Dash0NotificationChannel) DeepCopy() *Dash0NotificationChannel {
	if in == nil {
		return nil
	}
	out := new(Dash0NotificationChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0NotificationChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0NotificationChannelDisplay) DeepCopyInto(out *Dash0NotificationChannelDisplay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0NotificationChannelDisplay.
func (in *Dash0NotificationChannelDisplay) DeepCopy() *Dash0NotificationChannelDisplay {
	if in == nil {
		return nil
	}
	out := new(Dash0NotificationChannelDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0NotificationChannelList) DeepCopyInto(out *Dash0NotificationChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0NotificationChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0NotificationChannelList.
func (in *Dash0NotificationChannelList) DeepCopy() *Dash0NotificationChannelList {
	if in == nil {
		return nil
	}
	out := new(Dash0NotificationChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0NotificationChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0NotificationChannelRouting) DeepCopyInto(out *Dash0NotificationChannelRouting) {
	*out = *in
	if in.Assets != nil {
		in, out := &in.Assets, &out.Assets
		*out = make([]Dash0NotificationChannelRoutingAsset, len(*in))
		copy(*out, *in)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]Dash0NotificationChannelRoutingFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0NotificationChannelRouting.
func (in *Dash0NotificationChannelRouting) DeepCopy() *Dash0NotificationChannelRouting {
	if in == nil {
		return nil
	}
	out := new(Dash0NotificationChannelRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0NotificationChannelRoutingAsset) DeepCopyInto(out *Dash0NotificationChannelRoutingAsset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0NotificationChannelRoutingAsset.
func (in *Dash0NotificationChannelRoutingAsset) DeepCopy() *Dash0NotificationChannelRoutingAsset {
	if in == nil {
		return nil
	}
	out := new(Dash0NotificationChannelRoutingAsset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0NotificationChannelRoutingFilter) DeepCopyInto(out *Dash0NotificationChannelRoutingFilter) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0NotificationChannelRoutingFilter.
func (in *Dash0NotificationChannelRoutingFilter) DeepCopy() *Dash0NotificationChannelRoutingFilter {
	if in == nil {
		return nil
	}
	out := new(Dash0NotificationChannelRoutingFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0NotificationChannelSpec) DeepCopyInto(out *Dash0NotificationChannelSpec) {
	*out = *in
	out.Display = in.Display
	if in.SlackConfig != nil {
		in, out := &in.SlackConfig, &out.SlackConfig
		*out = new(SlackConfig)
		**out = **in
	}
	if in.SlackBotConfig != nil {
		in, out := &in.SlackBotConfig, &out.SlackBotConfig
		*out = new(SlackBotConfig)
		**out = **in
	}
	if in.EmailV2Config != nil {
		in, out := &in.EmailV2Config, &out.EmailV2Config
		*out = new(EmailV2Config)
		(*in).DeepCopyInto(*out)
	}
	if in.WebhookConfig != nil {
		in, out := &in.WebhookConfig, &out.WebhookConfig
		*out = new(WebhookConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.IncidentioConfig != nil {
		in, out := &in.IncidentioConfig, &out.IncidentioConfig
		*out = new(IncidentioConfig)
		**out = **in
	}
	if in.OpsgenieConfig != nil {
		in, out := &in.OpsgenieConfig, &out.OpsgenieConfig
		*out = new(OpsgenieConfig)
		**out = **in
	}
	if in.PagerdutyConfig != nil {
		in, out := &in.PagerdutyConfig, &out.PagerdutyConfig
		*out = new(PagerdutyConfig)
		**out = **in
	}
	if in.TeamsWebhookConfig != nil {
		in, out := &in.TeamsWebhookConfig, &out.TeamsWebhookConfig
		*out = new(TeamsWebhookConfig)
		**out = **in
	}
	if in.DiscordWebhookConfig != nil {
		in, out := &in.DiscordWebhookConfig, &out.DiscordWebhookConfig
		*out = new(DiscordWebhookConfig)
		**out = **in
	}
	if in.GoogleChatWebhookConfig != nil {
		in, out := &in.GoogleChatWebhookConfig, &out.GoogleChatWebhookConfig
		*out = new(GoogleChatWebhookConfig)
		**out = **in
	}
	if in.IlertConfig != nil {
		in, out := &in.IlertConfig, &out.IlertConfig
		*out = new(IlertConfig)
		**out = **in
	}
	if in.AllQuietConfig != nil {
		in, out := &in.AllQuietConfig, &out.AllQuietConfig
		*out = new(AllQuietConfig)
		**out = **in
	}
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(Dash0NotificationChannelRouting)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0NotificationChannelSpec.
func (in *Dash0NotificationChannelSpec) DeepCopy() *Dash0NotificationChannelSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0NotificationChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0NotificationChannelStatus) DeepCopyInto(out *Dash0NotificationChannelStatus) {
	*out = *in
	in.SynchronizedAt.DeepCopyInto(&out.SynchronizedAt)
	if in.ValidationIssues != nil {
		in, out := &in.ValidationIssues, &out.ValidationIssues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SynchronizationResults != nil {
		in, out := &in.SynchronizationResults, &out.SynchronizationResults
		*out = make([]Dash0NotificationChannelSynchronizationResultPerEndpointAndDataset, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0NotificationChannelStatus.
func (in *Dash0NotificationChannelStatus) DeepCopy() *Dash0NotificationChannelStatus {
	if in == nil {
		return nil
	}
	out := new(Dash0NotificationChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0NotificationChannelSynchronizationResultPerEndpointAndDataset) DeepCopyInto(out *Dash0NotificationChannelSynchronizationResultPerEndpointAndDataset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0NotificationChannelSynchronizationResultPerEndpointAndDataset.
func (in *Dash0NotificationChannelSynchronizationResultPerEndpointAndDataset) DeepCopy() *Dash0NotificationChannelSynchronizationResultPerEndpointAndDataset {
	if in == nil {
		return nil
	}
	out := new(Dash0NotificationChannelSynchronizationResultPerEndpointAndDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscordWebhookConfig) DeepCopyInto(out *DiscordWebhookConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscordWebhookConfig.
func (in *DiscordWebhookConfig) DeepCopy() *DiscordWebhookConfig {
	if in == nil {
		return nil
	}
	out := new(DiscordWebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailV2Config) DeepCopyInto(out *EmailV2Config) {
	*out = *in
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Plaintext != nil {
		in, out := &in.Plaintext, &out.Plaintext
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailV2Config.
func (in *EmailV2Config) DeepCopy() *EmailV2Config {
	if in == nil {
		return nil
	}
	out := new(EmailV2Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChatWebhookConfig) DeepCopyInto(out *GoogleChatWebhookConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChatWebhookConfig.
func (in *GoogleChatWebhookConfig) DeepCopy() *GoogleChatWebhookConfig {
	if in == nil {
		return nil
	}
	out := new(GoogleChatWebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IlertConfig) DeepCopyInto(out *IlertConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IlertConfig.
func (in *IlertConfig) DeepCopy() *IlertConfig {
	if in == nil {
		return nil
	}
	out := new(IlertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentioConfig) DeepCopyInto(out *IncidentioConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentioConfig.
func (in *IncidentioConfig) DeepCopy() *IncidentioConfig {
	if in == nil {
		return nil
	}
	out := new(IncidentioConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentWorkloads) DeepCopyInto(out *InstrumentWorkloads) {
	*out = *in
	in.TraceContext.DeepCopyInto(&out.TraceContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentWorkloads.
func (in *InstrumentWorkloads) DeepCopy() *InstrumentWorkloads {
	if in == nil {
		return nil
	}
	out := new(InstrumentWorkloads)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieConfig) DeepCopyInto(out *OpsgenieConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieConfig.
func (in *OpsgenieConfig) DeepCopy() *OpsgenieConfig {
	if in == nil {
		return nil
	}
	out := new(OpsgenieConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyConfig) DeepCopyInto(out *PagerdutyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyConfig.
func (in *PagerdutyConfig) DeepCopy() *PagerdutyConfig {
	if in == nil {
		return nil
	}
	out := new(PagerdutyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackBotConfig) DeepCopyInto(out *SlackBotConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackBotConfig.
func (in *SlackBotConfig) DeepCopy() *SlackBotConfig {
	if in == nil {
		return nil
	}
	out := new(SlackBotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackConfig) DeepCopyInto(out *SlackConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackConfig.
func (in *SlackConfig) DeepCopy() *SlackConfig {
	if in == nil {
		return nil
	}
	out := new(SlackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamsWebhookConfig) DeepCopyInto(out *TeamsWebhookConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamsWebhookConfig.
func (in *TeamsWebhookConfig) DeepCopy() *TeamsWebhookConfig {
	if in == nil {
		return nil
	}
	out := new(TeamsWebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceContext) DeepCopyInto(out *TraceContext) {
	*out = *in
	if in.Propagators != nil {
		in, out := &in.Propagators, &out.Propagators
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceContext.
func (in *TraceContext) DeepCopy() *TraceContext {
	if in == nil {
		return nil
	}
	out := new(TraceContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FollowRedirects != nil {
		in, out := &in.FollowRedirects, &out.FollowRedirects
		*out = new(bool)
		**out = **in
	}
	if in.AllowInsecure != nil {
		in, out := &in.AllowInsecure, &out.AllowInsecure
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}
