//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/dash0hq/dash0-operator/api/operator/common"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0Monitoring) DeepCopyInto(out *Dash0Monitoring) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0Monitoring.
func (in *Dash0Monitoring) DeepCopy() *Dash0Monitoring {
	if in == nil {
		return nil
	}
	out := new(Dash0Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0Monitoring) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0MonitoringList) DeepCopyInto(out *Dash0MonitoringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dash0Monitoring, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0MonitoringList.
func (in *Dash0MonitoringList) DeepCopy() *Dash0MonitoringList {
	if in == nil {
		return nil
	}
	out := new(Dash0MonitoringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dash0MonitoringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0MonitoringSpec) DeepCopyInto(out *Dash0MonitoringSpec) {
	*out = *in
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = new(common.Export)
		(*in).DeepCopyInto(*out)
	}
	in.InstrumentWorkloads.DeepCopyInto(&out.InstrumentWorkloads)
	in.LogCollection.DeepCopyInto(&out.LogCollection)
	in.EventCollection.DeepCopyInto(&out.EventCollection)
	in.PrometheusScraping.DeepCopyInto(&out.PrometheusScraping)
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(common.Filter)
		(*in).DeepCopyInto(*out)
	}
	if in.Transform != nil {
		in, out := &in.Transform, &out.Transform
		*out = new(common.Transform)
		(*in).DeepCopyInto(*out)
	}
	if in.NormalizedTransformSpec != nil {
		in, out := &in.NormalizedTransformSpec, &out.NormalizedTransformSpec
		*out = new(common.NormalizedTransformSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SynchronizePersesDashboards != nil {
		in, out := &in.SynchronizePersesDashboards, &out.SynchronizePersesDashboards
		*out = new(bool)
		**out = **in
	}
	if in.SynchronizePrometheusRules != nil {
		in, out := &in.SynchronizePrometheusRules, &out.SynchronizePrometheusRules
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0MonitoringSpec.
func (in *Dash0MonitoringSpec) DeepCopy() *Dash0MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(Dash0MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dash0MonitoringStatus) DeepCopyInto(out *Dash0MonitoringStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PreviousInstrumentWorkloads.DeepCopyInto(&out.PreviousInstrumentWorkloads)
	if in.PersesDashboardSynchronizationResults != nil {
		in, out := &in.PersesDashboardSynchronizationResults, &out.PersesDashboardSynchronizationResults
		*out = make(map[string]common.PersesDashboardSynchronizationResults, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PrometheusRuleSynchronizationResults != nil {
		in, out := &in.PrometheusRuleSynchronizationResults, &out.PrometheusRuleSynchronizationResults
		*out = make(map[string]common.PrometheusRuleSynchronizationResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dash0MonitoringStatus.
func (in *Dash0MonitoringStatus) DeepCopy() *Dash0MonitoringStatus {
	if in == nil {
		return nil
	}
	out := new(Dash0MonitoringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentWorkloads) DeepCopyInto(out *InstrumentWorkloads) {
	*out = *in
	in.TraceContext.DeepCopyInto(&out.TraceContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentWorkloads.
func (in *InstrumentWorkloads) DeepCopy() *InstrumentWorkloads {
	if in == nil {
		return nil
	}
	out := new(InstrumentWorkloads)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceContext) DeepCopyInto(out *TraceContext) {
	*out = *in
	if in.Propagators != nil {
		in, out := &in.Propagators, &out.Propagators
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceContext.
func (in *TraceContext) DeepCopy() *TraceContext {
	if in == nil {
		return nil
	}
	out := new(TraceContext)
	in.DeepCopyInto(out)
	return out
}
