// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Vendored from the dash0 monorepo
// (modules/proto/internal/outboundconnector/outboundconnector.proto), kept in sync with the copy in
// images/agent0-connector/src/proto/outboundconnector.proto. Only the go_package option differs (it points at the
// e2e mock module).
//
// To re-vendor: copy the upstream file, set the go_package option below to the
// outbound-connector-mock module path, then run `make proto-gen-outbound-connector-mock` from the repo root.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: proto/outboundconnector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An ID to associate requests with their responses. Carried end-to-end
	// (Kafka -> outbound-connector -> operator and back).
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The executable name. For now only "kubectl" is allowed.
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// List of arguments.
	Arguments []string `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// W3C traceparent header for distributed trace propagation.
	Traceparent   string `protobuf:"bytes,4,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_outboundconnector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_outboundconnector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_outboundconnector_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *CommandRequest) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

type CommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An ID to associate requests with their responses.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The exit code of the command invocation. It should be ignored when the command execution
	// timed out (see the timeout field).
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// The captured stdout stream.
	Stdout string `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// The captured stderr stream.
	Stderr string `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Whether the command execution timed out.
	Timeout       bool `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_outboundconnector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_outboundconnector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_outboundconnector_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResponse) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

var File_proto_outboundconnector_proto protoreflect.FileDescriptor

const file_proto_outboundconnector_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/outboundconnector.proto\x12\x11outboundconnector\"\x89\x01\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\x12 \n" +
	"\vtraceparent\x18\x04 \x01(\tR\vtraceparent\"\x97\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\bR\atimeout2\x83\x01\n" +
	"\x18OutboundConnectorService\x12g\n" +
	"\x1aSubscribeToCommandRequests\x12\".outboundconnector.CommandResponse\x1a!.outboundconnector.CommandRequest(\x010\x01B\x1fZ\x1doutbound-connector-mock/protob\x06proto3"

var (
	file_proto_outboundconnector_proto_rawDescOnce sync.Once
	file_proto_outboundconnector_proto_rawDescData []byte
)

func file_proto_outboundconnector_proto_rawDescGZIP() []byte {
	file_proto_outboundconnector_proto_rawDescOnce.Do(func() {
		file_proto_outboundconnector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_outboundconnector_proto_rawDesc), len(file_proto_outboundconnector_proto_rawDesc)))
	})
	return file_proto_outboundconnector_proto_rawDescData
}

var file_proto_outboundconnector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_outboundconnector_proto_goTypes = []any{
	(*CommandRequest)(nil),  // 0: outboundconnector.CommandRequest
	(*CommandResponse)(nil), // 1: outboundconnector.CommandResponse
}
var file_proto_outboundconnector_proto_depIdxs = []int32{
	1, // 0: outboundconnector.OutboundConnectorService.SubscribeToCommandRequests:input_type -> outboundconnector.CommandResponse
	0, // 1: outboundconnector.OutboundConnectorService.SubscribeToCommandRequests:output_type -> outboundconnector.CommandRequest
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_outboundconnector_proto_init() }
func file_proto_outboundconnector_proto_init() {
	if File_proto_outboundconnector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_outboundconnector_proto_rawDesc), len(file_proto_outboundconnector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_outboundconnector_proto_goTypes,
		DependencyIndexes: file_proto_outboundconnector_proto_depIdxs,
		MessageInfos:      file_proto_outboundconnector_proto_msgTypes,
	}.Build()
	File_proto_outboundconnector_proto = out.File
	file_proto_outboundconnector_proto_goTypes = nil
	file_proto_outboundconnector_proto_depIdxs = nil
}
