// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Vendored from the dash0 monorepo
// (modules/proto/internal/outboundconnector/outboundconnector.proto), kept in sync with the copy in
// images/agent0-connector/src/proto/outboundconnector.proto. Only the go_package option differs (it points at the
// e2e mock module).
//
// To re-vendor: copy the upstream file, set the go_package option below to the
// outbound-connector-mock module path, then run `make proto-gen-outbound-connector-mock` from the repo root.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: proto/outboundconnector.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutboundConnectorService_SubscribeToCommandRequests_FullMethodName = "/outboundconnector.OutboundConnectorService/SubscribeToCommandRequests"
)

// OutboundConnectorServiceClient is the client API for OutboundConnectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutboundConnectorServiceClient interface {
	// SubscribeToCommandRequests is opened by clients like the Dash0 operator running inside a
	// monitored cluster. After establishing the connection, outbound-connector (the server
	// component in this interaction) pushes CommandRequest messages for that client down the
	// stream. The client executes them in its context (e.g. in the target Kubernetes cluster)
	// and sends back the result of each command execution as a CommandResponse.
	//
	// Clients identify themselves via the dash0-client-id gRPC metadata key (a unique
	// identifier for the client instance) when opening the stream.
	SubscribeToCommandRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandResponse, CommandRequest], error)
}

type outboundConnectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutboundConnectorServiceClient(cc grpc.ClientConnInterface) OutboundConnectorServiceClient {
	return &outboundConnectorServiceClient{cc}
}

func (c *outboundConnectorServiceClient) SubscribeToCommandRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandResponse, CommandRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OutboundConnectorService_ServiceDesc.Streams[0], OutboundConnectorService_SubscribeToCommandRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandResponse, CommandRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OutboundConnectorService_SubscribeToCommandRequestsClient = grpc.BidiStreamingClient[CommandResponse, CommandRequest]

// OutboundConnectorServiceServer is the server API for OutboundConnectorService service.
// All implementations must embed UnimplementedOutboundConnectorServiceServer
// for forward compatibility.
type OutboundConnectorServiceServer interface {
	// SubscribeToCommandRequests is opened by clients like the Dash0 operator running inside a
	// monitored cluster. After establishing the connection, outbound-connector (the server
	// component in this interaction) pushes CommandRequest messages for that client down the
	// stream. The client executes them in its context (e.g. in the target Kubernetes cluster)
	// and sends back the result of each command execution as a CommandResponse.
	//
	// Clients identify themselves via the dash0-client-id gRPC metadata key (a unique
	// identifier for the client instance) when opening the stream.
	SubscribeToCommandRequests(grpc.BidiStreamingServer[CommandResponse, CommandRequest]) error
	mustEmbedUnimplementedOutboundConnectorServiceServer()
}

// UnimplementedOutboundConnectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutboundConnectorServiceServer struct{}

func (UnimplementedOutboundConnectorServiceServer) SubscribeToCommandRequests(grpc.BidiStreamingServer[CommandResponse, CommandRequest]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToCommandRequests not implemented")
}
func (UnimplementedOutboundConnectorServiceServer) mustEmbedUnimplementedOutboundConnectorServiceServer() {
}
func (UnimplementedOutboundConnectorServiceServer) testEmbeddedByValue() {}

// UnsafeOutboundConnectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutboundConnectorServiceServer will
// result in compilation errors.
type UnsafeOutboundConnectorServiceServer interface {
	mustEmbedUnimplementedOutboundConnectorServiceServer()
}

func RegisterOutboundConnectorServiceServer(s grpc.ServiceRegistrar, srv OutboundConnectorServiceServer) {
	// If the following call pancis, it indicates UnimplementedOutboundConnectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutboundConnectorService_ServiceDesc, srv)
}

func _OutboundConnectorService_SubscribeToCommandRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OutboundConnectorServiceServer).SubscribeToCommandRequests(&grpc.GenericServerStream[CommandResponse, CommandRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OutboundConnectorService_SubscribeToCommandRequestsServer = grpc.BidiStreamingServer[CommandResponse, CommandRequest]

// OutboundConnectorService_ServiceDesc is the grpc.ServiceDesc for OutboundConnectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutboundConnectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outboundconnector.OutboundConnectorService",
	HandlerType: (*OutboundConnectorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToCommandRequests",
			Handler:       _OutboundConnectorService_SubscribeToCommandRequests_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/outboundconnector.proto",
}
