// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Vendored from the dash0 monorepo (modules/proto/internal/synthetictasks/synthetictasks.proto). Only the go_package
// option differs (it points at the e2e mock module).
//
// To re-vendor: copy the upstream file, set the go_package option below to the
// outbound-connector-mock module path, then run `make proto-gen-outbound-connector-mock-synthetics` from the repo root.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/synthetictasks.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyntheticTaskService_Subscribe_FullMethodName = "/synthetictasks.SyntheticTaskService/Subscribe"
)

// SyntheticTaskServiceClient is the client API for SyntheticTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SyntheticTaskService dispatches synthetic check tasks to workers running in a
// customer network (a "private location"). It ships in the public edge-proxy image,
// so this is a customer-facing contract.
type SyntheticTaskServiceClient interface {
	// Subscribe is opened by a private-location worker; connectivity is outbound-only.
	// The worker authenticates with an organization-scoped bearer token in the
	// `authorization` gRPC metadata header, in the form `Bearer <token>`.
	//
	// The first WorkerMessage MUST be a Hello; the server rejects the stream otherwise.
	// The worker MUST then send Heartbeat at a fixed interval for as long as the stream
	// is open, including while it executes a task. It MUST answer every TaskRequest with
	// exactly one TaskResult carrying the same task_id.
	//
	// Delivery is at-least-once and scoped to one stream. A worker MUST abandon any task
	// still outstanding when its stream closes, and MUST NOT send that task's result on a
	// later stream; the server ignores a task_id it did not dispatch on the stream the
	// result arrives on. The server may dispatch the same underlying work again as a new
	// task with a new task_id, so a task can execute more than once.
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ServerMessage], error)
}

type syntheticTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyntheticTaskServiceClient(cc grpc.ClientConnInterface) SyntheticTaskServiceClient {
	return &syntheticTaskServiceClient{cc}
}

func (c *syntheticTaskServiceClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyntheticTaskService_ServiceDesc.Streams[0], SyntheticTaskService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyntheticTaskService_SubscribeClient = grpc.BidiStreamingClient[WorkerMessage, ServerMessage]

// SyntheticTaskServiceServer is the server API for SyntheticTaskService service.
// All implementations must embed UnimplementedSyntheticTaskServiceServer
// for forward compatibility.
//
// SyntheticTaskService dispatches synthetic check tasks to workers running in a
// customer network (a "private location"). It ships in the public edge-proxy image,
// so this is a customer-facing contract.
type SyntheticTaskServiceServer interface {
	// Subscribe is opened by a private-location worker; connectivity is outbound-only.
	// The worker authenticates with an organization-scoped bearer token in the
	// `authorization` gRPC metadata header, in the form `Bearer <token>`.
	//
	// The first WorkerMessage MUST be a Hello; the server rejects the stream otherwise.
	// The worker MUST then send Heartbeat at a fixed interval for as long as the stream
	// is open, including while it executes a task. It MUST answer every TaskRequest with
	// exactly one TaskResult carrying the same task_id.
	//
	// Delivery is at-least-once and scoped to one stream. A worker MUST abandon any task
	// still outstanding when its stream closes, and MUST NOT send that task's result on a
	// later stream; the server ignores a task_id it did not dispatch on the stream the
	// result arrives on. The server may dispatch the same underlying work again as a new
	// task with a new task_id, so a task can execute more than once.
	Subscribe(grpc.BidiStreamingServer[WorkerMessage, ServerMessage]) error
	mustEmbedUnimplementedSyntheticTaskServiceServer()
}

// UnimplementedSyntheticTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyntheticTaskServiceServer struct{}

func (UnimplementedSyntheticTaskServiceServer) Subscribe(grpc.BidiStreamingServer[WorkerMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSyntheticTaskServiceServer) mustEmbedUnimplementedSyntheticTaskServiceServer() {}
func (UnimplementedSyntheticTaskServiceServer) testEmbeddedByValue()                              {}

// UnsafeSyntheticTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyntheticTaskServiceServer will
// result in compilation errors.
type UnsafeSyntheticTaskServiceServer interface {
	mustEmbedUnimplementedSyntheticTaskServiceServer()
}

func RegisterSyntheticTaskServiceServer(s grpc.ServiceRegistrar, srv SyntheticTaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedSyntheticTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyntheticTaskService_ServiceDesc, srv)
}

func _SyntheticTaskService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyntheticTaskServiceServer).Subscribe(&grpc.GenericServerStream[WorkerMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyntheticTaskService_SubscribeServer = grpc.BidiStreamingServer[WorkerMessage, ServerMessage]

// SyntheticTaskService_ServiceDesc is the grpc.ServiceDesc for SyntheticTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyntheticTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synthetictasks.SyntheticTaskService",
	HandlerType: (*SyntheticTaskServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SyntheticTaskService_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/synthetictasks.proto",
}
