// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0
//
// Vendored from the dash0 monorepo (modules/proto/internal/synthetictasks/synthetictasks.proto). Only the go_package
// option differs (it points at the e2e mock module).
//
// To re-vendor: copy the upstream file, set the go_package option below to the
// outbound-connector-mock module path, then run `make proto-gen-outbound-connector-mock-synthetics` from the repo root.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/synthetictasks.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskKind enumerates the kinds of task a worker can execute. It is the unit of capability
// negotiation, so a kind is deprecated before dispatch stops and a removed value stays
// reserved.
type TaskKind int32

const (
	TaskKind_TASK_KIND_UNSPECIFIED TaskKind = 0
	// An HTTP synthetic check, carried as TaskRequest.http_check.
	TaskKind_TASK_KIND_HTTP_CHECK TaskKind = 1
)

// Enum value maps for TaskKind.
var (
	TaskKind_name = map[int32]string{
		0: "TASK_KIND_UNSPECIFIED",
		1: "TASK_KIND_HTTP_CHECK",
	}
	TaskKind_value = map[string]int32{
		"TASK_KIND_UNSPECIFIED": 0,
		"TASK_KIND_HTTP_CHECK":  1,
	}
)

func (x TaskKind) Enum() *TaskKind {
	p := new(TaskKind)
	*p = x
	return p
}

func (x TaskKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_synthetictasks_proto_enumTypes[0].Descriptor()
}

func (TaskKind) Type() protoreflect.EnumType {
	return &file_proto_synthetictasks_proto_enumTypes[0]
}

func (x TaskKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskKind.Descriptor instead.
func (TaskKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{0}
}

// TaskFailureReason categorizes why a worker could not execute a task.
type TaskFailureReason int32

const (
	TaskFailureReason_TASK_FAILURE_REASON_UNSPECIFIED TaskFailureReason = 0
	// The worker does not implement the payload kind it received.
	TaskFailureReason_TASK_FAILURE_REASON_UNSUPPORTED_TASK_KIND TaskFailureReason = 1
	// The payload did not decode, or its schema version is one the worker cannot handle.
	TaskFailureReason_TASK_FAILURE_REASON_INVALID_PAYLOAD TaskFailureReason = 2
	// The worker hit TaskRequest.timeout before the task finished.
	TaskFailureReason_TASK_FAILURE_REASON_TIMEOUT TaskFailureReason = 3
	// The worker failed for a reason the other values do not cover.
	TaskFailureReason_TASK_FAILURE_REASON_INTERNAL TaskFailureReason = 4
)

// Enum value maps for TaskFailureReason.
var (
	TaskFailureReason_name = map[int32]string{
		0: "TASK_FAILURE_REASON_UNSPECIFIED",
		1: "TASK_FAILURE_REASON_UNSUPPORTED_TASK_KIND",
		2: "TASK_FAILURE_REASON_INVALID_PAYLOAD",
		3: "TASK_FAILURE_REASON_TIMEOUT",
		4: "TASK_FAILURE_REASON_INTERNAL",
	}
	TaskFailureReason_value = map[string]int32{
		"TASK_FAILURE_REASON_UNSPECIFIED":           0,
		"TASK_FAILURE_REASON_UNSUPPORTED_TASK_KIND": 1,
		"TASK_FAILURE_REASON_INVALID_PAYLOAD":       2,
		"TASK_FAILURE_REASON_TIMEOUT":               3,
		"TASK_FAILURE_REASON_INTERNAL":              4,
	}
)

func (x TaskFailureReason) Enum() *TaskFailureReason {
	p := new(TaskFailureReason)
	*p = x
	return p
}

func (x TaskFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_synthetictasks_proto_enumTypes[1].Descriptor()
}

func (TaskFailureReason) Type() protoreflect.EnumType {
	return &file_proto_synthetictasks_proto_enumTypes[1]
}

func (x TaskFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskFailureReason.Descriptor instead.
func (TaskFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{1}
}

// WorkerMessage is everything a worker can send on the stream.
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_TaskResult
	Message       isWorkerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_proto_synthetictasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMessage() isWorkerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

type isWorkerMessage_Message interface {
	isWorkerMessage_Message()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,3,opt,name=task_result,json=taskResult,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Message() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Message() {}

func (*WorkerMessage_TaskResult) isWorkerMessage_Message() {}

// ServerMessage is everything the server can send on the stream.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_TaskRequest
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_synthetictasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetTaskRequest() *TaskRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_TaskRequest); ok {
			return x.TaskRequest
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_TaskRequest struct {
	TaskRequest *TaskRequest `protobuf:"bytes,1,opt,name=task_request,json=taskRequest,proto3,oneof"`
}

func (*ServerMessage_TaskRequest) isServerMessage_Message() {}

// Hello identifies the worker and its capabilities. It MUST be the first message on
// the stream and MUST NOT be sent again on the same stream.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The customer-chosen location this worker belongs to, unique only within the
	// worker's organization. The server resolves it to the location's Dash0-assigned
	// identity, which a worker never learns.
	//
	// This is a client assertion, not a proven identity: the bearer token authenticates
	// the organization and nothing finer, so any worker holding it can name any location
	// in that organization. Treat it as a routing key within the authenticated
	// organization, never as an authorization decision.
	LocationId string `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	// Unique per worker instance. A worker MUST derive it from something that changes on
	// every restart, such as the Kubernetes pod UID or a UUID generated at startup.
	WorkerId string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Free-form version of the worker build, for diagnostics. The server MUST NOT make
	// dispatch decisions from it.
	WorkerVersion string `protobuf:"bytes,3,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	// The task kinds the server may dispatch to this worker. A worker MUST NOT advertise
	// a kind it cannot run. A kind the server does not recognize is ignored.
	SupportedTaskKinds []TaskKind `protobuf:"varint,4,rep,packed,name=supported_task_kinds,json=supportedTaskKinds,proto3,enum=synthetictasks.TaskKind" json:"supported_task_kinds,omitempty"`
	// The payload apiVersions this worker can decode, per task kind. A worker SHOULD announce
	// an entry for every kind it lists in supported_task_kinds; an entry for a kind it did
	// not list is ignored.
	//
	// Empty means the worker predates this field, not that it decodes nothing: a worker
	// built before this field existed cannot announce anything. The server MUST then fall
	// back to the oldest apiVersion whose deprecation window is still open.
	SupportedApiVersions []*SupportedApiVersions `protobuf:"bytes,5,rep,name=supported_api_versions,json=supportedApiVersions,proto3" json:"supported_api_versions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_synthetictasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Hello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Hello) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

func (x *Hello) GetSupportedTaskKinds() []TaskKind {
	if x != nil {
		return x.SupportedTaskKinds
	}
	return nil
}

func (x *Hello) GetSupportedApiVersions() []*SupportedApiVersions {
	if x != nil {
		return x.SupportedApiVersions
	}
	return nil
}

// SupportedApiVersions announces the payload apiVersions a worker can decode for one task
// kind.
type SupportedApiVersions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  TaskKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=synthetictasks.TaskKind" json:"kind,omitempty"`
	// The apiVersions of the kind's params schema this worker can decode, for example
	// "dash0.com/v1alpha1". The server MUST dispatch only a version present here.
	ApiVersions   []string `protobuf:"bytes,2,rep,name=api_versions,json=apiVersions,proto3" json:"api_versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedApiVersions) Reset() {
	*x = SupportedApiVersions{}
	mi := &file_proto_synthetictasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedApiVersions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedApiVersions) ProtoMessage() {}

func (x *SupportedApiVersions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedApiVersions.ProtoReflect.Descriptor instead.
func (*SupportedApiVersions) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{3}
}

func (x *SupportedApiVersions) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_TASK_KIND_UNSPECIFIED
}

func (x *SupportedApiVersions) GetApiVersions() []string {
	if x != nil {
		return x.ApiVersions
	}
	return nil
}

// Heartbeat reports that the worker is alive. It carries no fields; capacity and
// readiness signals are deferred.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_synthetictasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{4}
}

// TaskRequest asks a worker to execute one task.
type TaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates this request with its TaskResult. Unique per dispatch and opaque to the
	// worker: re-dispatched work arrives as a new task_id, never a reused one.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// W3C traceparent header. The worker MUST use it as the parent of the spans it
	// produces for this task.
	Traceparent string `protobuf:"bytes,2,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	// Bounds the whole task, separate from any timeout inside the payload. The worker
	// MUST answer with TASK_FAILURE_REASON_TIMEOUT once it elapses.
	Timeout *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// The server only sets an arm the worker advertised in Hello. A worker that receives
	// an arm it does not know MUST answer with TASK_FAILURE_REASON_UNSUPPORTED_TASK_KIND.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*TaskRequest_HttpCheck
	Payload       isTaskRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_synthetictasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{5}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *TaskRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TaskRequest) GetPayload() isTaskRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskRequest) GetHttpCheck() *HttpCheckTask {
	if x != nil {
		if x, ok := x.Payload.(*TaskRequest_HttpCheck); ok {
			return x.HttpCheck
		}
	}
	return nil
}

type isTaskRequest_Payload interface {
	isTaskRequest_Payload()
}

type TaskRequest_HttpCheck struct {
	HttpCheck *HttpCheckTask `protobuf:"bytes,4,opt,name=http_check,json=httpCheck,proto3,oneof"`
}

func (*TaskRequest_HttpCheck) isTaskRequest_Payload() {}

// HttpCheckTask carries the parameters of an HTTP synthetic check.
type HttpCheckTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON encoding of the Dash0 OpenAPI schema `syntheticchecks.HttpRequestParams`.
	Params []byte `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// The apiVersion of the `params` schema, for example "dash0.com/v1alpha1". The server
	// MUST pick one the receiving worker announced in Hello.supported_api_versions. A worker
	// that cannot handle the apiVersion it receives MUST still answer with
	// TASK_FAILURE_REASON_INVALID_PAYLOAD.
	ApiVersion    string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpCheckTask) Reset() {
	*x = HttpCheckTask{}
	mi := &file_proto_synthetictasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpCheckTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpCheckTask) ProtoMessage() {}

func (x *HttpCheckTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpCheckTask.ProtoReflect.Descriptor instead.
func (*HttpCheckTask) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{6}
}

func (x *HttpCheckTask) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *HttpCheckTask) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

// TaskResult reports the outcome of exactly one TaskRequest.
type TaskResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The task_id of the TaskRequest this answers.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// A check that ran and observed a failing response is a successful task; that failure
	// belongs in the check result. Set `failure` only for a task the worker could not
	// execute at all.
	//
	// Types that are valid to be assigned to Result:
	//
	//	*TaskResult_HttpCheck
	//	*TaskResult_Failure
	Result        isTaskResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_synthetictasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetResult() isTaskResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResult) GetHttpCheck() *HttpCheckResult {
	if x != nil {
		if x, ok := x.Result.(*TaskResult_HttpCheck); ok {
			return x.HttpCheck
		}
	}
	return nil
}

func (x *TaskResult) GetFailure() *TaskFailure {
	if x != nil {
		if x, ok := x.Result.(*TaskResult_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isTaskResult_Result interface {
	isTaskResult_Result()
}

type TaskResult_HttpCheck struct {
	HttpCheck *HttpCheckResult `protobuf:"bytes,2,opt,name=http_check,json=httpCheck,proto3,oneof"`
}

type TaskResult_Failure struct {
	Failure *TaskFailure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*TaskResult_HttpCheck) isTaskResult_Result() {}

func (*TaskResult_Failure) isTaskResult_Result() {}

// HttpCheckResult carries the outcome of an executed HTTP synthetic check.
type HttpCheckResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON encoding of the Dash0 OpenAPI schema `syntheticchecks.HttpRequestResult`.
	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// The apiVersion of the `result` schema, for example "dash0.com/v1alpha1".
	ApiVersion    string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpCheckResult) Reset() {
	*x = HttpCheckResult{}
	mi := &file_proto_synthetictasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpCheckResult) ProtoMessage() {}

func (x *HttpCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpCheckResult.ProtoReflect.Descriptor instead.
func (*HttpCheckResult) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{8}
}

func (x *HttpCheckResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HttpCheckResult) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

// TaskFailure reports that the worker could not execute the task.
type TaskFailure struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason TaskFailureReason      `protobuf:"varint,1,opt,name=reason,proto3,enum=synthetictasks.TaskFailureReason" json:"reason,omitempty"`
	// Detail for diagnostics. Callers MUST NOT parse it; branch on `reason`.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFailure) Reset() {
	*x = TaskFailure{}
	mi := &file_proto_synthetictasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFailure) ProtoMessage() {}

func (x *TaskFailure) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synthetictasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFailure.ProtoReflect.Descriptor instead.
func (*TaskFailure) Descriptor() ([]byte, []int) {
	return file_proto_synthetictasks_proto_rawDescGZIP(), []int{9}
}

func (x *TaskFailure) GetReason() TaskFailureReason {
	if x != nil {
		return x.Reason
	}
	return TaskFailureReason_TASK_FAILURE_REASON_UNSPECIFIED
}

func (x *TaskFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_synthetictasks_proto protoreflect.FileDescriptor

const file_proto_synthetictasks_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/synthetictasks.proto\x12\x0esynthetictasks\x1a\x1egoogle/protobuf/duration.proto\"\xc3\x01\n" +
	"\rWorkerMessage\x12-\n" +
	"\x05hello\x18\x01 \x01(\v2\x15.synthetictasks.HelloH\x00R\x05hello\x129\n" +
	"\theartbeat\x18\x02 \x01(\v2\x19.synthetictasks.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\vtask_result\x18\x03 \x01(\v2\x1a.synthetictasks.TaskResultH\x00R\n" +
	"taskResultB\t\n" +
	"\amessage\"\\\n" +
	"\rServerMessage\x12@\n" +
	"\ftask_request\x18\x01 \x01(\v2\x1b.synthetictasks.TaskRequestH\x00R\vtaskRequestB\t\n" +
	"\amessage\"\x94\x02\n" +
	"\x05Hello\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12%\n" +
	"\x0eworker_version\x18\x03 \x01(\tR\rworkerVersion\x12J\n" +
	"\x14supported_task_kinds\x18\x04 \x03(\x0e2\x18.synthetictasks.TaskKindR\x12supportedTaskKinds\x12Z\n" +
	"\x16supported_api_versions\x18\x05 \x03(\v2$.synthetictasks.SupportedApiVersionsR\x14supportedApiVersions\"g\n" +
	"\x14SupportedApiVersions\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.synthetictasks.TaskKindR\x04kind\x12!\n" +
	"\fapi_versions\x18\x02 \x03(\tR\vapiVersions\"\v\n" +
	"\tHeartbeat\"\xc8\x01\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12 \n" +
	"\vtraceparent\x18\x02 \x01(\tR\vtraceparent\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12>\n" +
	"\n" +
	"http_check\x18\x04 \x01(\v2\x1d.synthetictasks.HttpCheckTaskH\x00R\thttpCheckB\t\n" +
	"\apayload\"H\n" +
	"\rHttpCheckTask\x12\x16\n" +
	"\x06params\x18\x01 \x01(\fR\x06params\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\"\xaa\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12@\n" +
	"\n" +
	"http_check\x18\x02 \x01(\v2\x1f.synthetictasks.HttpCheckResultH\x00R\thttpCheck\x127\n" +
	"\afailure\x18\x03 \x01(\v2\x1b.synthetictasks.TaskFailureH\x00R\afailureB\b\n" +
	"\x06result\"J\n" +
	"\x0fHttpCheckResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\"b\n" +
	"\vTaskFailure\x129\n" +
	"\x06reason\x18\x01 \x01(\x0e2!.synthetictasks.TaskFailureReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*?\n" +
	"\bTaskKind\x12\x19\n" +
	"\x15TASK_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_KIND_HTTP_CHECK\x10\x01*\xd3\x01\n" +
	"\x11TaskFailureReason\x12#\n" +
	"\x1fTASK_FAILURE_REASON_UNSPECIFIED\x10\x00\x12-\n" +
	")TASK_FAILURE_REASON_UNSUPPORTED_TASK_KIND\x10\x01\x12'\n" +
	"#TASK_FAILURE_REASON_INVALID_PAYLOAD\x10\x02\x12\x1f\n" +
	"\x1bTASK_FAILURE_REASON_TIMEOUT\x10\x03\x12 \n" +
	"\x1cTASK_FAILURE_REASON_INTERNAL\x10\x042e\n" +
	"\x14SyntheticTaskService\x12M\n" +
	"\tSubscribe\x12\x1d.synthetictasks.WorkerMessage\x1a\x1d.synthetictasks.ServerMessage(\x010\x01B\x1fZ\x1doutbound-connector-mock/protob\x06proto3"

var (
	file_proto_synthetictasks_proto_rawDescOnce sync.Once
	file_proto_synthetictasks_proto_rawDescData []byte
)

func file_proto_synthetictasks_proto_rawDescGZIP() []byte {
	file_proto_synthetictasks_proto_rawDescOnce.Do(func() {
		file_proto_synthetictasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_synthetictasks_proto_rawDesc), len(file_proto_synthetictasks_proto_rawDesc)))
	})
	return file_proto_synthetictasks_proto_rawDescData
}

var file_proto_synthetictasks_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_synthetictasks_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_synthetictasks_proto_goTypes = []any{
	(TaskKind)(0),                // 0: synthetictasks.TaskKind
	(TaskFailureReason)(0),       // 1: synthetictasks.TaskFailureReason
	(*WorkerMessage)(nil),        // 2: synthetictasks.WorkerMessage
	(*ServerMessage)(nil),        // 3: synthetictasks.ServerMessage
	(*Hello)(nil),                // 4: synthetictasks.Hello
	(*SupportedApiVersions)(nil), // 5: synthetictasks.SupportedApiVersions
	(*Heartbeat)(nil),            // 6: synthetictasks.Heartbeat
	(*TaskRequest)(nil),          // 7: synthetictasks.TaskRequest
	(*HttpCheckTask)(nil),        // 8: synthetictasks.HttpCheckTask
	(*TaskResult)(nil),           // 9: synthetictasks.TaskResult
	(*HttpCheckResult)(nil),      // 10: synthetictasks.HttpCheckResult
	(*TaskFailure)(nil),          // 11: synthetictasks.TaskFailure
	(*durationpb.Duration)(nil),  // 12: google.protobuf.Duration
}
var file_proto_synthetictasks_proto_depIdxs = []int32{
	4,  // 0: synthetictasks.WorkerMessage.hello:type_name -> synthetictasks.Hello
	6,  // 1: synthetictasks.WorkerMessage.heartbeat:type_name -> synthetictasks.Heartbeat
	9,  // 2: synthetictasks.WorkerMessage.task_result:type_name -> synthetictasks.TaskResult
	7,  // 3: synthetictasks.ServerMessage.task_request:type_name -> synthetictasks.TaskRequest
	0,  // 4: synthetictasks.Hello.supported_task_kinds:type_name -> synthetictasks.TaskKind
	5,  // 5: synthetictasks.Hello.supported_api_versions:type_name -> synthetictasks.SupportedApiVersions
	0,  // 6: synthetictasks.SupportedApiVersions.kind:type_name -> synthetictasks.TaskKind
	12, // 7: synthetictasks.TaskRequest.timeout:type_name -> google.protobuf.Duration
	8,  // 8: synthetictasks.TaskRequest.http_check:type_name -> synthetictasks.HttpCheckTask
	10, // 9: synthetictasks.TaskResult.http_check:type_name -> synthetictasks.HttpCheckResult
	11, // 10: synthetictasks.TaskResult.failure:type_name -> synthetictasks.TaskFailure
	1,  // 11: synthetictasks.TaskFailure.reason:type_name -> synthetictasks.TaskFailureReason
	2,  // 12: synthetictasks.SyntheticTaskService.Subscribe:input_type -> synthetictasks.WorkerMessage
	3,  // 13: synthetictasks.SyntheticTaskService.Subscribe:output_type -> synthetictasks.ServerMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_synthetictasks_proto_init() }
func file_proto_synthetictasks_proto_init() {
	if File_proto_synthetictasks_proto != nil {
		return
	}
	file_proto_synthetictasks_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_TaskResult)(nil),
	}
	file_proto_synthetictasks_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_TaskRequest)(nil),
	}
	file_proto_synthetictasks_proto_msgTypes[5].OneofWrappers = []any{
		(*TaskRequest_HttpCheck)(nil),
	}
	file_proto_synthetictasks_proto_msgTypes[7].OneofWrappers = []any{
		(*TaskResult_HttpCheck)(nil),
		(*TaskResult_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_synthetictasks_proto_rawDesc), len(file_proto_synthetictasks_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_synthetictasks_proto_goTypes,
		DependencyIndexes: file_proto_synthetictasks_proto_depIdxs,
		EnumInfos:         file_proto_synthetictasks_proto_enumTypes,
		MessageInfos:      file_proto_synthetictasks_proto_msgTypes,
	}.Build()
	File_proto_synthetictasks_proto = out.File
	file_proto_synthetictasks_proto_goTypes = nil
	file_proto_synthetictasks_proto_depIdxs = nil
}
