# SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dash0-operator-dotnet-test-statefulset
  {{- with .Values.statefulset.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.statefulset.selector }}
  serviceName: "{{ include "dotnet-test-app.chartName" . }}-dotnet-test-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.selector }}
        test.label/key: "label-value"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.statefulset.targetPort }}"
        test.annotation/key: "annotation value"
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: PORT
              # See https://opentelemetry.io/docs/zero-code/dotnet/instrumentations/#instrumentation-options
              value: "{{ .Values.statefulset.targetPort }}"
            - name: OTEL_DOTNET_EXPERIMENTAL_ASPNETCORE_DISABLE_URL_QUERY_REDACTION
              value: "true"
            - name: OTEL_DOTNET_EXPERIMENTAL_ASPNET_DISABLE_URL_QUERY_REDACTION
              value: "true"
            - name: OTEL_DOTNET_EXPERIMENTAL_HTTPCLIENT_DISABLE_URL_QUERY_REDACTION
              value: "true"
          ports:
            - containerPort: {{ .Values.statefulset.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.statefulset.targetPort }}
            initialDelaySeconds: 1
            periodSeconds: 1
{{- end }}
