apiVersion: v1
kind: Pod
metadata:
  name: dotnet-demo-app
spec:
  containers:
  - name: app
    image: aspnetapp
    imagePullPolicy: IfNotPresent
    env:
    - name: OTEL_LOGS_EXPORTER
      value: console
    - name: OTEL_METRICS_EXPORTER
      value: console
    - name: OTELTRACES_EXPORTER
      value: console
    - name: DASH0_DEBUG
      value: "true"
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
        ephemeral-storage: 500Mi
      requests:
        cpu: 250m
        memory: 128Mi
        ephemeral-storage: 500Mi
  restartPolicy: Always