# SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: dash0-operator-dotnet-test-replicaset-service
spec:
  selector:
    app: dash0-operator-dotnet-test-replicaset-app
  ports:
    - port: 1409
      targetPort: 1409
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dash0-operator-dotnet-test-replicaset
  labels:
    app: dash0-operator-dotnet-test-replicaset-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash0-operator-dotnet-test-replicaset-app
  template:
    metadata:
      labels:
        app: dash0-operator-dotnet-test-replicaset-app
        test.label/key: "label-value"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1409"
        test.annotation/key: "annotation value"
    spec:
      containers:
        - name: dash0-operator-dotnet-test-replicaset-app
          image: "dash0-operator-dotnet-test-app:latest"
          env:
            - name: PORT
              value: "1409"
            - name: DASH0_EXPERIMENTAL_DOTNET_INJECTION
              value: "true"
            # See https://opentelemetry.io/docs/zero-code/dotnet/instrumentations/#instrumentation-options
            - name: OTEL_DOTNET_EXPERIMENTAL_ASPNETCORE_DISABLE_URL_QUERY_REDACTION
              value: "true"
            - name: OTEL_DOTNET_EXPERIMENTAL_ASPNET_DISABLE_URL_QUERY_REDACTION
              value: "true"
            - name: OTEL_DOTNET_EXPERIMENTAL_HTTPCLIENT_DISABLE_URL_QUERY_REDACTION
              value: "true"
          ports:
            - containerPort: 1409
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 500Mi
            requests:
              cpu: 200m
              memory: 128Mi
              ephemeral-storage: 500Mi
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: 1409
            initialDelaySeconds: 1
            periodSeconds: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash0-operator-dotnet-test-replicaset-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /replicaset(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dash0-operator-dotnet-test-replicaset-service
            port:
              number: 1409
