#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname ${BASH_SOURCE})"/../..

gofmt -s -w .

# This could be a simple "goimports -w ." without find&grep, if only .goimportsignore would work on a per-project basis.
# See https://github.com/golang/go/issues/42965.
find . -iname \*.go | grep -v zz_generated.deepcopy.go | xargs goimports -w
