// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

package kubectl

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"strings"
	"time"

	pb "github.com/dash0hq/dash0-operator/images/agent0-connector/proto"
	"github.com/dash0hq/dash0-operator/images/agent0-connector/tracecontext"
)

const (
	// kubectlCommand is the only executable command requests are allowed to invoke.
	kubectlCommand = "kubectl"

	// defaultCommandTimeout is the default value for commandTimeout, bounding the execution time of a single kubectl
	// invocation.
	defaultCommandTimeout = 30 * time.Second

	// exitCodeRejected is reported for command requests that are rejected before execution (wrong command, not a
	// read-only kubectl subcommand, ...).
	exitCodeRejected int32 = 1

	// exitCodeNotExecutable is reported when kubectl could not be executed at all (e.g. the binary is missing),
	// mirroring the shell convention for "command not executable".
	exitCodeNotExecutable int32 = 127

	// exitCodeTimedOut is reported when a kubectl invocation exceeds commandTimeout. exec.CommandContext kills the
	// process with SIGKILL when the deadline is exceeded, and the OS reports a signal-killed process with exit code -1
	// (exitErr.ExitCode() returns -1 because the process did not exit normally). That is the value surfaced to the
	// backend for a timeout.
	exitCodeTimedOut int32 = -1

	// KubectlTmpEnvVarName names the environment variable that points at a writable directory for kubectl's caches.
	// kubectl stores its discovery and HTTP caches below $HOME/.kube/cache; the container's root filesystem is
	// read-only, so the operator sets this to a writable emptyDir volume (and the image defaults it to /tmp). The
	// kubectl subprocess then runs with HOME set to this directory (see kubectlEnv).
	KubectlTmpEnvVarName = "DASH0_KUBECTL_TMP"

	// maxOutputBytesPerStream caps how many bytes of stdout and stderr (each) are captured from a kubectl invocation.
	// The output is buffered in memory and sent back in a single gRPC message, so unbounded output (e.g. "kubectl get
	// -A -o yaml" on a large cluster, or a noisy "kubectl logs") could exhaust the pod's memory limit or exceed gRPC's
	// default maximum message size. Output beyond this limit is discarded and a truncation notice is appended.
	maxOutputBytesPerStream = 1024 * 1024 // 1 MiB
)

// commandTimeout bounds the execution time of a single kubectl invocation.
var commandTimeout = defaultCommandTimeout

// allowedFlags is the allowlist of kubectl flags command requests may use, keyed without leading dashes (shorthands and
// long names are separate entries); the value reports whether the flag consumes the following argument as its value.
// Command requests are generated by an agent, so the argument stream is arbitrary: any flag not listed here is
// rejected, which keeps flags added by future kubectl releases from widening what the connector accepts. Absent
// (and therefore rejected) are flags that redirect the request target (--raw), select a different cluster or identity
// (--server, --kubeconfig, --context, --as*, --token, ...), weaken transport security, read local files (-f, -k),
// stream (-w, --follow), or log the HTTP request and response bodies and thereby the contents of any resource
// (-v at verbosity 8 and above).
var allowedFlags = map[string]bool{
	// global
	"namespace": true, "n": true,
	"all-namespaces": false, "A": false,
	"request-timeout": true,
	"help":            false, "h": false,

	// resource selection and output shaping, shared by several subcommands
	"output": true, "o": true,
	"selector": true, "l": true,
	"field-selector":              true,
	"sort-by":                     true,
	"chunk-size":                  true,
	"subresource":                 true,
	"label-columns":               true,
	"L":                           true,
	"template":                    true,
	"allow-missing-template-keys": false,
	"no-headers":                  false,
	"show-labels":                 false,
	"show-kind":                   false,
	"show-managed-fields":         false,
	"ignore-not-found":            false,

	// describe
	"show-events": false,

	// logs
	"container": true, "c": true,
	"since":            true,
	"since-time":       true,
	"tail":             true,
	"limit-bytes":      true,
	"max-log-requests": true,
	"all-containers":   false,
	"previous":         false, "p": false,
	"timestamps":    false,
	"prefix":        false,
	"ignore-errors": false,

	// top
	"containers":           false,
	"sum":                  false,
	"use-protocol-buffers": false,

	// events
	"for":   true,
	"types": true,

	// explain
	"api-version": true,
	"recursive":   false,

	// api-resources
	"api-group":  true,
	"verbs":      true,
	"categories": true,
	"namespaced": false,
	"cached":     false,

	// version
	"client": false,
}

// ExecuteCommandRequest validates and executes a CommandRequest and returns the corresponding CommandResponse.
// Requests that do not pass validation (not kubectl, not a read-only subcommand, ...) are rejected without being
// executed and the rejection reason is reported on stderr with a non-zero exit code.
func ExecuteCommandRequest(
	ctx context.Context,
	logger *slog.Logger,
	kubectlTmpDir string,
	req *pb.CommandRequest,
) *pb.CommandResponse {
	tc := tracecontext.ParseTraceparent(req.GetTraceparent())
	if tc.TraceID != "" {
		logger = logger.With("traceID", tc.TraceID, "spanID", tc.SpanID)
	}

	parsed, validationErr := validateCommandAndParseArguments(req)
	if validationErr != nil {
		logger.Warn("rejecting command request", "requestId", req.GetRequestId(), "reason", validationErr.Error())
		return &pb.CommandResponse{
			RequestId: req.GetRequestId(),
			ExitCode:  exitCodeRejected,
			Stderr:    fmt.Sprintf("dash0 agent0-connector rejected the command: %s", validationErr),
		}
	}

	execCtx, cancel := context.WithTimeout(ctx, commandTimeout)
	defer cancel()

	stdout, stderr, err := runKubectl(execCtx, kubectlTmpDir, req.GetArguments(), maxOutputBytesPerStream)

	resp := &pb.CommandResponse{
		RequestId: req.GetRequestId(),
		Stdout:    stdout.String(),
		Stderr:    stderr.String(),
	}

	// A deadline on execCtx (as opposed to the parent ctx being cancelled on shutdown) means the command exceeded
	// commandTimeout and was killed.
	timedOut := errors.Is(execCtx.Err(), context.DeadlineExceeded)

	exitCode, additionalStdErrMsg := postProcessRunResult(err, timedOut)
	resp.ExitCode = exitCode
	resp.Timeout = timedOut

	// The response is redacted before any notice is appended, so that redaction only ever operates on kubectl's own
	// output.
	redactionErr := redactSecretsInResponse(parsed, resp, stdout.truncated)
	if redactionErr != nil {
		logger.Error(
			"withholding a command response that could not be redacted",
			"requestId", req.GetRequestId(),
			"reason", redactionErr.Error(),
		)
		withholdResponse(resp, redactionErr)
		return resp
	}

	if stdout.truncated {
		resp.Stdout = withTruncationNotice(resp.Stdout)
	}
	if stderr.truncated {
		resp.Stderr = withTruncationNotice(resp.Stderr)
	}
	if additionalStdErrMsg != "" {
		resp.Stderr = appendLine(resp.Stderr, additionalStdErrMsg)
	}

	return resp
}

// runKubectl runs kubectl with the given arguments, capturing at most limit bytes of stdout and of stderr, and returns
// the two capped buffers together with the error reported by exec (nil if kubectl exited with code zero).
func runKubectl(
	ctx context.Context,
	kubectlTmpDir string,
	arguments []string,
	limit int,
) (*cappedBuffer, *cappedBuffer, error) {
	stdout := &cappedBuffer{limit: limit}
	stderr := &cappedBuffer{limit: limit}
	cmd := exec.CommandContext(ctx, kubectlCommand, arguments...)
	cmd.Env = kubectlEnv(kubectlTmpDir)
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	return stdout, stderr, cmd.Run()
}

// kubectlEnv returns the environment for the kubectl subprocess. By default, kubectl writes its discovery and HTTP
// caches to $HOME/.kube/cache, which is on the read-only root filesystem in this pod. kubectlTmpDir (resolved once at
// startup, see resolveKubectlTmpDir) points to a writable directory, so kubectl's HOME is redirected there to let
// caching work.
func kubectlEnv(kubectlTmpDir string) []string {
	return append(os.Environ(), "HOME="+kubectlTmpDir)
}

// postProcessRunResult maps the error (if any) returned by cmd.Run() to the exit code reported back to the backend.
// When the command exceeded commandTimeout (timedOut) or kubectl could not be executed at all (binary missing, ...) it
// also returns an explanatory message to append to stderr; otherwise the returned message is empty.
func postProcessRunResult(err error, timedOut bool) (exitCode int32, execFailureMessage string) {
	switch {
	case timedOut:
		return exitCodeTimedOut, fmt.Sprintf("dash0 agent0-connector aborted kubectl after the %s timeout", commandTimeout)
	case err == nil:
		return 0, ""
	case isExitError(err):
		var exitErr *exec.ExitError
		errors.As(err, &exitErr)
		return int32(exitErr.ExitCode()), ""
	default:
		return exitCodeNotExecutable, fmt.Sprintf("dash0 agent0-connector failed to execute kubectl: %s", err)
	}
}

// normalizeOutputFormat reduces an output format value to its lower-cased base type, dropping any "=..." suffix used by
// composite formats (jsonpath, go-template, custom-columns).
func normalizeOutputFormat(value string) string {
	value = strings.TrimSpace(value)
	if idx := strings.Index(value, "="); idx >= 0 {
		value = value[:idx]
	}
	return strings.ToLower(value)
}

func isExitError(err error) bool {
	var exitErr *exec.ExitError
	return errors.As(err, &exitErr)
}

// appendLine appends line to existing, separating them with a newline if existing is non-empty.
func appendLine(existing, line string) string {
	if existing == "" {
		return line
	}
	return existing + "\n" + line
}

// withTruncationNotice appends a notice that the output was truncated at maxOutputBytesPerStream bytes.
func withTruncationNotice(output string) string {
	return appendLine(
		output,
		fmt.Sprintf("[dash0 agent0-connector truncated the output at %d bytes]", maxOutputBytesPerStream),
	)
}

// cappedBuffer is an io.Writer that captures up to limit bytes and discards the rest, recording whether any data was
// discarded. It always reports the full write length so the kubectl subprocess never sees a short write (which os/exec
// would surface as an error); the discarded bytes are simply dropped.
type cappedBuffer struct {
	limit     int
	buf       bytes.Buffer
	truncated bool
}

func (c *cappedBuffer) Write(p []byte) (int, error) {
	if remaining := c.limit - c.buf.Len(); remaining > 0 {
		if len(p) > remaining {
			c.buf.Write(p[:remaining])
			c.truncated = true
		} else {
			c.buf.Write(p)
		}
	} else if len(p) > 0 {
		c.truncated = true
	}
	return len(p), nil
}

func (c *cappedBuffer) String() string {
	return c.buf.String()
}
