// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Validation for kubectl command requests. Checks whether a command kubectl invocation is allowed or if it needs to be
// rejected.

package kubectl

import (
	"errors"
	"fmt"
	"maps"
	"slices"
	"strings"

	pb "github.com/dash0hq/dash0-operator/images/agent0-connector/proto"
)

// allowedKubectlCommands is the allowlist of kubectl commands the executor is allowed to run. Everything else
// is rejected. The list deliberately contains only kubectl commands that read cluster state and never mutate it. This
// is additional defense-in-depth on top of the read-only RBAC (get & list only) granted to the agent0-connector service
// account.
//
// Allowed kubectl commands can be further restricted via allowedSubcommandsPerKubectlCommand.
var allowedKubectlCommands = map[string]struct{}{
	"api-resources": {},
	"auth":          {},
	"api-versions":  {},
	"cluster-info":  {},
	"describe":      {},
	"events":        {},
	"explain":       {},
	"get":           {},
	"logs":          {},
	"top":           {},
	"version":       {},
}

var allowedKubectlCommandsHumanReadable = func() string {
	allCmds := slices.Sorted(maps.Keys(allowedKubectlCommands))
	allowedCmdsString := fmt.Sprintf("%q", allCmds[0])
	for idx, kubectlCmd := range allCmds {
		if idx > 0 && idx < len(allCmds)-1 {
			allowedCmdsString += fmt.Sprintf(", %q", kubectlCmd)
		} else if idx == len(allCmds)-1 {
			allowedCmdsString += fmt.Sprintf(" and %q", kubectlCmd)
		}
	}
	return allowedCmdsString
}()

// allowedSubcommandsPerKubectlCommand lists the allowed kubectl commands that may only be invoked with one of the
// listed subcommands. Every other subcommand is rejected for that kubectl command. This way a future kubectl release
// adding a new subcommand does not widen what the connector accepts. The empty string stands for the bare subcommand,
// that is, an invocation of that particular kubectl command without any positional argument. A kubctl command that may
// only be invoked bare must list the empty string as its only entry.
var allowedSubcommandsPerKubectlCommand = map[string][]string{
	// "auth can-i" only reports what the agent0-connector's service account is allowed to do, but its sibling
	// subcommand "auth reconcile" creates and updates roles and role bindings, hence "auth" is only allowed with the
	// subcommand "can-i".
	"auth": {"can-i"},

	// "cluster-info" is read-only and harmless on its own, but its only subcommand, "kubectl cluster-info dump", writes
	// the full JSON of the nodes, events, replication controllers, services, daemon sets, deployments, replica sets and
	// pods of a namespace or the whole cluster to stdout. This response cannot be redacted reliably, hence
	// "cluster-info" is only allowed in its bare form.
	"cluster-info": {""},
}

// allowedOutputFormats is the allowlist of output formats command requests may use via -o/--output, keyed by the
// normalized base type (see normalizeOutputFormat). Command requests are generated by an agent, so the argument stream
// is arbitrary: any format not listed here is rejected, which keeps formats added by future kubectl releases from
// widening what the connector accepts.
//
// Absent (and therefore rejected) are the formats that take their template from a file: "go-template-file",
// "templatefile", "jsonpath-file" and "custom-columns-file" render the referenced file. They could be abused to read
// arbitrary files in the agent0-connector's container, such as its service account token or its environment. Plus,
// these would refer to a file that exists in agent0's local file system, not in the local file system of
// agent0-connector, hence none of these formats would work anyway.
var allowedOutputFormats = map[string]struct{}{
	"":                 {}, // the default, human-readable table output
	"custom-columns":   {},
	"go-template":      {},
	"json":             {},
	"jsonpath":         {},
	"jsonpath-as-json": {},
	"kyaml":            {},
	"name":             {},
	"template":         {},
	"wide":             {},
	"yaml":             {},
}

// contentFreeOutputFormats are the output formats that do not require secret redaction, i.e. that allow listing
// resources or checking for the presence of a particular one without exposing their content. Any other output format
// (yaml, json, jsonpath, go-template, custom-columns, ...) can serialize the content.
// Such a request
// * is outright rejected in validation.go when it targets a sensitive resource (e.g. a Kubernetes secret)
// * might get parts of its response (secrets, auth tokens, credentials etc.) redacted
var contentFreeOutputFormats = map[string]struct{}{
	"":     {}, // the default, human-readable table output
	"name": {},
	"wide": {},
}

// redactableOutputFormats is the allowlist of output formats that
// * can be parsed and rendered
// * can be reliably redacted because they do not reshape the response
//
// Absent (and therefore rejected for those resource types) are the formats that let the request reshape the response:
// "go-template" and its alias "template", "jsonpath", "jsonpath-as-json" and "custom-columns", as well as the
// --template flag, which selects go-template output even without -o.
//
// "kyaml" is deliberately absent as well: it renders values verbatim and would be redacted correctly, but it is a
// recent addition to kubectl that the redaction is not exercised against yet. It stays allowed for every other
// resource type via allowedOutputFormats.
var redactableOutputFormats = map[string]struct{}{
	"json": {},
	"yaml": {},
}

// unredactableOutputFormatReasons holds the output formats that are rejected for a resource type that can contain
// secrets for a reason other than being able to reshape the response. Without it the rejection would tell the caller
// that the format reshapes values, which is wrong for these and points them away from a format that would work.
var unredactableOutputFormatReasons = map[string]string{
	"kyaml": "the connector does not redact this output format yet",
}

// safeSortByPathPrefixes are the top-level fields a --sort-by expression may address when the request targets a
// resource type that can contain secrets, or a sensitive resource type. Neither the metadata nor the status of such a
// resource holds a credential, while its spec holds every field the response redacts, and the data of a secret sits
// outside both prefixes.
var safeSortByPathPrefixes = []string{"metadata", "status"}

var safeSortByPathPrefixesHumanReadable = func() string {
	quoted := make([]string, 0, len(safeSortByPathPrefixes))
	for _, prefix := range safeSortByPathPrefixes {
		quoted = append(quoted, fmt.Sprintf("%q", prefix))
	}
	return strings.Join(quoted, " or ")
}()

// unsafeSortByPathPrefix is the one field below safeSortByPathPrefixes that a --sort-by expression may not address:
// kubectl apply stores a verbatim copy of the applied manifest, credentials included, in the
// "kubectl.kubernetes.io/last-applied-configuration" annotation, see redactAnnotations.
const unsafeSortByPathPrefix = "metadata.annotations"

// safeOrRedactableOutputFormats is the allowlist of output formats a command request may use when it targets a
// resource type that can contain secrets (see resourceTypesWithSecrets). It lists the formats that never contain
// resource content with secrets (e.g. "", "name", "wide") and the formats that can be reliably redacted because they
// do not reshape the response ("json", "yaml").
var safeOrRedactableOutputFormats = func() map[string]struct{} {
	formats := maps.Clone(contentFreeOutputFormats)
	maps.Copy(formats, redactableOutputFormats)
	return formats
}()

// sensitiveResource describes how a resource type whose contents must not be exposed is guarded.
type sensitiveResource struct {
	// displayName names the resource in rejection messages.
	displayName string
}

var secretResource = sensitiveResource{displayName: "secret"}

// sensitiveResourceTypes maps the resource type names whose contents must not be exposed to their guard, in singular
// and plural form.
var sensitiveResourceTypes = map[string]sensitiveResource{
	"secret":  secretResource,
	"secrets": secretResource,
}

// validateCommandAndParseArguments parses the request's argument list and ensures the request invokes an allowed
// read-only kubectl command, and only uses allowed flags. It returns the parsed argument list, which the caller may
// reuse for further processing (e.g. redacting the response). If the request is allowed, the returned error is nil.
// If an error is returned, the error describes why the request is rejected. The returned argument list must not be
// used when the error is non-nil.
func validateCommandAndParseArguments(req *pb.CommandRequest) (kubectlArguments, error) {
	if reason, blocked := disallowedExecutableRequested(req); blocked {
		return kubectlArguments{}, errors.New(reason)
	}

	arguments := parseKubectlArguments(req.GetArguments())

	// The flags are checked first: which token is the kubctl command and which tokens reference resources depends on
	// knowing which flags consume the following argument as their value, which is only known for flags from the
	// allowlist.
	if len(arguments.disallowedFlags) > 0 {
		return kubectlArguments{}, fmt.Errorf("the kubectl flag %q is not allowed", arguments.disallowedFlags[0])
	}

	// Check the kubectl command first, reject any kubectl command that is not on the allowlist (allowedKubectlCommands).
	if reason, blocked := disallowedKubectlCommandRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if reason, blocked := disallowedSubcommandRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if format, disallowed := disallowedOutputFormat(arguments); disallowed {
		return kubectlArguments{}, fmt.Errorf("the kubectl output format %q is not allowed", format)
	}
	if reason, blocked := sensitiveContentRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if reason, blocked := unredactableOutputRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if reason, blocked := unsafeSortByRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if reason, blocked := unsafeSortByOfSensitiveResourceRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if reason, blocked := describeOfResourceTypeWithSecrets(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	return arguments, nil
}

func disallowedExecutableRequested(req *pb.CommandRequest) (string, bool) {
	if req.GetCommand() == "" {
		return fmt.Sprintf(
			"invalid command request without command, only the %q command is allowed",
			kubectlCommand,
		), true
	}
	if req.GetCommand() != kubectlCommand {
		return fmt.Sprintf(
			"only the command %q is allowed, but got %q",
			kubectlCommand,
			req.GetCommand(),
		), true
	}
	return "", false
}

func disallowedKubectlCommandRequested(parsed kubectlArguments) (string, bool) {
	if parsed.kubectlCommand == "" {
		// Invoking kubectl with no command at all - bare `kubectl`, or only global flags such as `kubectl --help` - is
		// allowed.
		return "", false
	}
	if _, allowed := allowedKubectlCommands[parsed.kubectlCommand]; !allowed {
		return fmt.Sprintf(
			"the kubectl command %q is not an allowed read-only command, the only allowed kubectl commands are %s",
			parsed.kubectlCommand,
			allowedKubectlCommandsHumanReadable,
		), true
	}
	return "", false
}

// disallowedSubcommandRequested reports whether the kubectl arguments invoke a kubectl command that is only allowed
// with a fixed set of subcommands, and the invocation uses a disallowed subcommand. It returns a human-readable reason
// if that is the case. See allowedSubcommandsPerKubectlCommand.
func disallowedSubcommandRequested(parsed kubectlArguments) (string, bool) {
	allowedSubcommands, restricted := allowedSubcommandsPerKubectlCommand[parsed.kubectlCommand]
	if !restricted {
		return "", false
	}
	requestedSubcommand := ""
	if len(parsed.positionalArguments) > 0 {
		requestedSubcommand = parsed.positionalArguments[0]
	}
	if slices.Contains(allowedSubcommands, requestedSubcommand) {
		return "", false
	}
	if slices.Equal(allowedSubcommands, []string{""}) {
		return fmt.Sprintf(
			"the kubectl command %q may only be used without additional subcommands, but got %q",
			parsed.kubectlCommand,
			requestedSubcommand,
		), true
	}
	if requestedSubcommand == "" {
		return fmt.Sprintf(
			"the kubectl command %q is only allowed without a subcommand, but the subcommand was %q",
			parsed.kubectlCommand,
			strings.Join(allowedSubcommands, "\" or \""),
		), true
	}
	return fmt.Sprintf(
		"the kubectl command %q is only allowed with the subcommand %q, but the subcommand was %q",
		parsed.kubectlCommand,
		strings.Join(allowedSubcommands, "\" or \""),
		requestedSubcommand,
	), true
}

// describeOfResourceTypeWithSecrets reports whether the kubectl arguments describe a resource that can contain
// secrets, returning a human-readable reason when they do. The describer renders a resource in a text format that is
// not meant to be parsed and for which no parser is available, so the connector cannot locate the credentials in its
// output in order to redact them.
func describeOfResourceTypeWithSecrets(parsed kubectlArguments) (string, bool) {
	if parsed.kubectlCommand != "describe" {
		return "", false
	}
	category, hasSecrets := targetsResourceTypeWithSecrets(parsed)
	if !hasSecrets {
		return "", false
	}
	return fmt.Sprintf(
		"describing %s is not supported, because it can contain %s which cannot be redacted from the output of "+
			"\"kubectl describe\"; read the resource with \"kubectl get ... -o yaml\" or \"-o json\" instead, which "+
			"returns the same content with %s redacted, and its events with "+
			"\"kubectl events --for <resource-type>/<name>\"",
		category.description,
		category.secrets,
		category.redactedContent,
	), true
}

// disallowedOutputFormat returns the first output format requested via -o/--output that is not in the
// allowedOutputFormats allowlist. Every occurrence of the flag is checked, not just the effective (last) one, so that
// an argument list in which any occurrence is disallowed is rejected without replicating kubectl's precedence rules.
func disallowedOutputFormat(parsed kubectlArguments) (string, bool) {
	for _, format := range parsed.outputFormats() {
		if _, allowed := allowedOutputFormats[format]; !allowed {
			return format, true
		}
	}
	return "", false
}

// sensitiveContentRequested reports whether the kubectl arguments would read the contents of a sensitive resource,
// returning a human-readable reason when they do. The default RBAC permissions disallow any access to secrets
// outright, even checking for the presence of a secret is not possible. However, overriding the default RBAC
// permissions with a custom cluster role is possible, and sensitiveContentRequested adds defense in-depth for those
// setups.
//
// Listing secrets (e.g. `kubectl get secrets`) and checking for the presence of a particular one
// (`kubectl get secret <name>`) are allowed (if the corresponding RBAC permissions are granted); serializing the data
// via an output format such as -o yaml/json/jsonpath/go-template/custom-columns (or --template) is not. Only the output
// format is checked, no kubectl command prints the data of a sensitive resource on its own: `kubectl describe secret`
// renders the key names and the byte counts of the values, not the values themselves. This is a fail-closed check:
// output formats that could expose the data are rejected even if a particular invocation would only read metadata, and
// a repeated output flag is rejected if any of its occurrences would expose the data.
func sensitiveContentRequested(parsed kubectlArguments) (string, bool) {
	resource, targeted := targetedSensitiveResource(parsed)
	if !targeted {
		return "", false
	}
	if parsed.outputIsContentFree() {
		return "", false
	}
	return fmt.Sprintf(
		"reading the contents of a %s is not allowed; listing %ss or checking for the presence of a particular %s is "+
			"supported, but serializing its data (e.g. via -o yaml/json/jsonpath/go-template/custom-columns) is not",
		resource.displayName,
		resource.displayName,
		resource.displayName,
	), true
}

// targetedSensitiveResource returns the guard for the first sensitive resource the kubectl arguments reference.
func targetedSensitiveResource(parsed kubectlArguments) (sensitiveResource, bool) {
	for _, resourceType := range parsed.resourceTypes {
		if resource, isSensitive := lookupSensitiveResourceType(resourceType); isSensitive {
			return resource, true
		}
	}
	return sensitiveResource{}, false
}

// lookupSensitiveResourceType returns the guard for the given resource type, accepting the singular and plural forms as
// well as fully qualified forms such as "secrets.v1." (the API group/version suffix is ignored).
func lookupSensitiveResourceType(resourceType string) (sensitiveResource, bool) {
	resource, isSensitive := sensitiveResourceTypes[normalizeResourceType(resourceType)]
	return resource, isSensitive
}

// unredactableOutputRequested reports whether the kubectl arguments would render a resource that can contain secrets
// in an output format whose result cannot be redacted reliably, returning a human-readable reason when they do. Every
// occurrence of -o/--output is checked, not just the effective (last) one, and --template counts as go-template output
// even without -o, mirroring outputIsContentFree.
func unredactableOutputRequested(parsed kubectlArguments) (string, bool) {
	category, hasSecrets := targetsResourceTypeWithSecrets(parsed)
	if !hasSecrets {
		return "", false
	}
	format, unredactable := unredactableOutputFormat(parsed)
	if !unredactable {
		return "", false
	}
	if reason, hasOwnReason := unredactableOutputFormatReasons[format]; hasOwnReason {
		return fmt.Sprintf(
			"the output format %q cannot be redacted reliably for %s, which can contain %s, because %s; reading such "+
				"a resource is supported with -o json/yaml/name/wide (or without an output format)",
			format,
			category.description,
			category.secrets,
			reason,
		), true
	}
	return fmt.Sprintf(
		"the output format %q cannot be redacted reliably for %s, which can contain %s; reading such a resource is "+
			"supported with -o json/yaml/name/wide (or without an output format), but not with a format that can "+
			"reshape its values (-o go-template/template/jsonpath/jsonpath-as-json/custom-columns or --template)",
		format,
		category.description,
		category.secrets,
	), true
}

// unsafeSortByRequested reports whether the kubectl arguments sort a resource that can contain secrets by a field the
// response redacts, returning a human-readable reason when they do. kubectl evaluates a --sort-by expression against
// the unredacted resources, so the connector cannot redact what the expression exposes: sorting by a redacted field
// leaks its order, and a filter expression such as {.spec.containers[0].env[?(@.value>"S")].name} turns the presence
// of a match into a comparison oracle that reveals the value character by character over several requests. Every
// occurrence of the flag is checked, not just the effective (last) one, mirroring unredactableOutputRequested.
func unsafeSortByRequested(parsed kubectlArguments) (string, bool) {
	category, hasSecrets := targetsResourceTypeWithSecrets(parsed)
	if !hasSecrets {
		return "", false
	}
	for _, expression := range parsed.valuesOf("sort-by") {
		if sortByExpressionIsSafe(expression) {
			continue
		}
		return fmt.Sprintf(
			"the --sort-by expression %q is not allowed for %s, which can contain %s; kubectl evaluates the "+
				"expression against the resources before the connector redacts them, so only a plain path below "+
				"%s may be sorted by, except %q (e.g. --sort-by=.metadata.name or --sort-by=.status.startTime)",
			expression,
			category.description,
			category.secrets,
			safeSortByPathPrefixesHumanReadable,
			unsafeSortByPathPrefix,
		), true
	}
	return "", false
}

// unsafeSortByOfSensitiveResourceRequested reports whether the kubectl arguments sort a sensitive resource by a field
// that can expose its content, returning a human-readable reason when they do. Listing secrets is allowed while reading
// their content is not (see sensitiveContentRequested), but kubectl evaluates a --sort-by expression against the
// resources before the connector ever sees the response: sorting by a field of "data" leaks its order, and a filter
// expression such as {.data[?(@>"S")]} turns the presence of a match into a comparison oracle that reveals the value
// over several requests. Every occurrence of the flag is checked, not just the effective (last) one, mirroring
// unsafeSortByRequested.
func unsafeSortByOfSensitiveResourceRequested(parsed kubectlArguments) (string, bool) {
	resource, targeted := targetedSensitiveResource(parsed)
	if !targeted {
		return "", false
	}
	for _, expression := range parsed.valuesOf("sort-by") {
		if sortByExpressionIsSafe(expression) {
			continue
		}
		return fmt.Sprintf(
			"the --sort-by expression %q is not allowed for a %s; kubectl evaluates the expression against the "+
				"resources before the connector sees them, so an expression that addresses the contents of the %s "+
				"would expose them; only a plain path below %s may be sorted by, except %q "+
				"(e.g. --sort-by=.metadata.name or --sort-by=.metadata.creationTimestamp)",
			expression,
			resource.displayName,
			resource.displayName,
			safeSortByPathPrefixesHumanReadable,
			unsafeSortByPathPrefix,
		), true
	}
	return "", false
}

// sortByExpressionIsSafe reports whether a --sort-by JSONPath expression addresses only fields that cannot hold a
// credential. It fails closed: anything it does not recognize as a plain path below safeSortByPathPrefixes is unsafe.
func sortByExpressionIsSafe(expression string) bool {
	path := normalizeSortByPath(expression)
	if path == "" {
		return false
	}
	// A filter expression, a wildcard, a recursive descent or a second path can address any field of the resource,
	// including the ones the response redacts.
	if strings.ContainsAny(path, "?*{}") || strings.Contains(path, "..") {
		return false
	}
	if isSortByPathBelow(path, unsafeSortByPathPrefix) {
		return false
	}
	return slices.ContainsFunc(safeSortByPathPrefixes, func(prefix string) bool {
		return isSortByPathBelow(path, prefix)
	})
}

// isSortByPathBelow reports whether a normalized --sort-by path addresses the given field or anything below it.
func isSortByPathBelow(path string, prefix string) bool {
	return path == prefix ||
		strings.HasPrefix(path, prefix+".") ||
		strings.HasPrefix(path, prefix+"[")
}

// normalizeSortByPath strips the optional surrounding braces and the leading dot of a --sort-by expression, so that
// "{.metadata.name}", ".metadata.name" and "metadata.name" all yield "metadata.name".
func normalizeSortByPath(expression string) string {
	path := strings.TrimSpace(expression)
	path = strings.TrimPrefix(path, "{")
	path = strings.TrimSuffix(path, "}")
	return strings.TrimPrefix(path, ".")
}

// unredactableOutputFormat returns the first output format that is not in the safeOrRedactableOutputFormats allowlist.
// The --template flag is reported as "go-template", the format it selects.
func unredactableOutputFormat(parsed kubectlArguments) (string, bool) {
	if parsed.hasTemplateFlag() {
		return "go-template", true
	}
	for _, format := range parsed.outputFormats() {
		if _, redactable := safeOrRedactableOutputFormats[format]; !redactable {
			return format, true
		}
	}
	return "", false
}
