// SPDX-FileCopyrightText: Copyright 2026 Dash0 Inc.
// SPDX-License-Identifier: Apache-2.0

// Validation for kubectl command requests. Checks whether a command kubectl invocation is allowed or if it needs to be
// rejected.

package kubectl

import (
	"errors"
	"fmt"
	"maps"
	"regexp"
	"slices"
	"strings"

	pb "github.com/dash0hq/dash0-operator/images/agent0-connector/proto"
)

// allowedKubectlCommands is the allowlist of kubectl commands the executor is allowed to run. Everything else
// is rejected. The list deliberately contains only kubectl commands that read cluster state and never mutate it. This
// is additional defense-in-depth on top of the read-only RBAC (get & list only) granted to the agent0-connector service
// account.
//
// Allowed kubectl commands can be further restricted via allowedSubcommandsPerKubectlCommand.
var allowedKubectlCommands = map[string]struct{}{
	"api-resources": {},
	"auth":          {},
	"api-versions":  {},
	"cluster-info":  {},
	"describe":      {},
	"events":        {},
	"explain":       {},
	"get":           {},
	"logs":          {},
	"top":           {},
	"version":       {},
}

var allowedKubectlCommandsHumanReadable = func() string {
	allCmds := slices.Sorted(maps.Keys(allowedKubectlCommands))
	allowedCmdsString := fmt.Sprintf("%q", allCmds[0])
	for idx, kubectlCmd := range allCmds {
		if idx > 0 && idx < len(allCmds)-1 {
			allowedCmdsString += fmt.Sprintf(", %q", kubectlCmd)
		} else if idx == len(allCmds)-1 {
			allowedCmdsString += fmt.Sprintf(" and %q", kubectlCmd)
		}
	}
	return allowedCmdsString
}()

// allowedSubcommandsPerKubectlCommand lists the allowed kubectl commands that may only be invoked with one of the
// listed subcommands. Every other subcommand is rejected for that kubectl command. This way a future kubectl release
// adding a new subcommand does not widen what the connector accepts. The empty string stands for the bare subcommand,
// that is, an invocation of that particular kubectl command without any positional argument. A kubctl command that may
// only be invoked bare must list the empty string as its only entry.
var allowedSubcommandsPerKubectlCommand = map[string][]string{
	// "auth can-i" only reports what the agent0-connector's service account is allowed to do, but its sibling
	// subcommand "auth reconcile" creates and updates roles and role bindings, hence "auth" is only allowed with the
	// subcommand "can-i".
	"auth": {"can-i"},

	// "cluster-info" is read-only and harmless on its own, but its only subcommand, "kubectl cluster-info dump", writes
	// the full JSON of the nodes, events, replication controllers, services, daemon sets, deployments, replica sets and
	// pods of a namespace or the whole cluster to stdout. This response cannot be redacted reliably, hence
	// "cluster-info" is only allowed in its bare form.
	"cluster-info": {""},
}

// outputFormatHandling states what the connector does with a response rendered in a particular output format.
type outputFormatHandling int

const (
	// outputFormatUnknown is the zero value, so that an output format that is not listed in knownOutputFormats is treated
	// as unknown (i.e. it is rejected), rather than accidentally being treated as content free.
	outputFormatUnknown outputFormatHandling = iota

	// outputFormatContentFree renders no resource content at all, hence there is nothing to redact. Such a request
	// lists resources or checks for the presence of a particular one, which is allowed even for a sensitive resource
	// type.
	outputFormatContentFree

	// outputFormatRedactable renders resource content in a form the connector can parse and redact. Requests using one
	// of these are processed.
	outputFormatRedactable

	// outputFormatUnredactable renders resource content the connector cannot parse and hence not redact. A request
	// using it is rejected.
	outputFormatUnredactable
)

// goTemplateOutputFormat is the output format the --template flag selects, even without -o.
const goTemplateOutputFormat = "go-template"

// supportedOutputFormatsHint names the output formats that do work, for the rejection of one that does not.
const supportedOutputFormatsHint = "reading a resource is supported with -o json/yaml/name/wide (or without an " +
	"output format)"

// knownOutputFormats lists every output format the connector knows. The key is the normalized base type (see
// normalizeOutputFormat). The map contains output formats that the connector allows in kubectl get commands, and
// rejected formats for which it returns a specific rejection message. Formats not listed here are rejeced with a
// general purpose message. This might be fine for some formats, so deliberately not listing a kubectl get format here
// can also be a valid decision. This also makes sure that formats added by future kubectl releases do not widen what
// the connector accepts.
//
// Command requests are generated by an agent, so the argument stream is arbitrary. The rejection messages are also
// tailored for an agent. The important bit is that we offer alternatives and tell the caller what it can do instead.
// The specific reason a format is rejected is not always relevant.
//
// Deliberately not listed (and thus rejected with a general purpose message) are
// - the formats that take their template from a file: "go-template-file",  "templatefile", "jsonpath-file" and
// "custom-columns-file" render the referenced file. They could be abused to read arbitrary files in the
// agent0-connector's container, such as its service account token or its environment. Plus, these would refer to a
// file that exists in agent0's local file system, not in the local file system of agent0-connector, hence none of these
// formats would work anyway.
// - "kyaml": it renders values verbatim and could be parsed and redacted like YAML, but we currently do not support it.
// It offers no real benefit to an agent over "-o yaml" or "-o json".
var knownOutputFormats = map[string]outputFormatHandling{
	"":     outputFormatContentFree, // the default, human-readable table output
	"name": outputFormatContentFree,
	"wide": outputFormatContentFree,

	"json": outputFormatRedactable,
	"yaml": outputFormatRedactable,

	"custom-columns":       outputFormatUnredactable,
	goTemplateOutputFormat: outputFormatUnredactable,
	"jsonpath":             outputFormatUnredactable,
	"jsonpath-as-json":     outputFormatUnredactable,
	"template":             outputFormatUnredactable,
}

// safeSortByPathPrefixes are the top-level fields a --sort-by expression may address. Neither the metadata nor the
// status of a resource holds a credential, while its spec holds every field the response redacts, and the data of a
// secret sits outside both prefixes.
var safeSortByPathPrefixes = []string{"metadata", "status"}

var safeSortByPathPrefixesHumanReadable = func() string {
	quoted := make([]string, 0, len(safeSortByPathPrefixes))
	for _, prefix := range safeSortByPathPrefixes {
		quoted = append(quoted, fmt.Sprintf("%q", prefix))
	}
	return strings.Join(quoted, " or ")
}()

// unsafeSortByPathPrefix is the one field below safeSortByPathPrefixes that a --sort-by expression may not address:
// kubectl apply stores a verbatim copy of the applied manifest, credentials included, in the
// "kubectl.kubernetes.io/last-applied-configuration" annotation, see redactAnnotationValues.
const unsafeSortByPathPrefix = "metadata.annotations"

// sensitiveResource describes how a resource type whose contents must not be exposed is guarded.
type sensitiveResource struct {
	// displayName names the resource in rejection messages.
	displayName string
}

var secretResource = sensitiveResource{displayName: "secret"}

// sensitiveResourceTypes maps the resource type names whose contents must not be exposed to their guard, in singular
// and plural form.
var sensitiveResourceTypes = map[string]sensitiveResource{
	"secret":  secretResource,
	"secrets": secretResource,
}

// validateCommandAndParseArguments parses the request's argument list and ensures the request invokes an allowed
// read-only kubectl command, and only uses allowed flags. It returns the parsed argument list, which the caller may
// reuse for further processing (e.g. redacting the response). If the request is allowed, the returned error is nil.
// If an error is returned, the error describes why the request is rejected. The returned argument list must not be
// used when the error is non-nil.
func validateCommandAndParseArguments(req *pb.CommandRequest) (kubectlArguments, error) {
	if reason, blocked := disallowedExecutableRequested(req); blocked {
		return kubectlArguments{}, errors.New(reason)
	}

	arguments := parseKubectlArguments(req.GetArguments())

	// The flags are checked first: which token is the kubctl command and which tokens reference resources depends on
	// knowing which flags consume the following argument as their value, which is only known for flags from the
	// allowlist.
	if len(arguments.disallowedFlags) > 0 {
		return kubectlArguments{}, fmt.Errorf("the kubectl flag %q is not allowed", arguments.disallowedFlags[0])
	}

	// Check the kubectl command first, reject any kubectl command that is not on the allowlist (allowedKubectlCommands).
	if reason, blocked := disallowedKubectlCommandRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if reason, blocked := disallowedSubcommandRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	// Checked before the output format, so that a request reading a secret is rejected with the reason that names what
	// makes the secret special, whatever output format it asks for.
	if reason, blocked := sensitiveContentRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if reason, blocked := unsupportedOutputFormatRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if reason, blocked := unsafeSortByRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	// Checked before describeRequested, so that describing a secret is rejected with the reason that names what makes
	// it worse than describing any other resource.
	if reason, blocked := describeOfSensitiveResourceRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	if reason, blocked := describeRequested(arguments); blocked {
		return kubectlArguments{}, errors.New(reason)
	}
	return arguments, nil
}

func disallowedExecutableRequested(req *pb.CommandRequest) (string, bool) {
	if req.GetCommand() == "" {
		return fmt.Sprintf(
			"invalid command request without command, only the %q command is allowed",
			kubectlCommand,
		), true
	}
	if req.GetCommand() != kubectlCommand {
		return fmt.Sprintf(
			"only the command %q is allowed, but got %q",
			kubectlCommand,
			req.GetCommand(),
		), true
	}
	return "", false
}

func disallowedKubectlCommandRequested(parsed kubectlArguments) (string, bool) {
	if parsed.kubectlCommand == "" {
		// Invoking kubectl with no command at all - bare `kubectl`, or only global flags such as `kubectl --help` - is
		// allowed.
		return "", false
	}
	if _, allowed := allowedKubectlCommands[parsed.kubectlCommand]; !allowed {
		return fmt.Sprintf(
			"the kubectl command %q is not an allowed read-only command, the only allowed kubectl commands are %s",
			parsed.kubectlCommand,
			allowedKubectlCommandsHumanReadable,
		), true
	}
	return "", false
}

// disallowedSubcommandRequested reports whether the kubectl arguments invoke a kubectl command that is only allowed
// with a fixed set of subcommands, and the invocation uses a disallowed subcommand. It returns a human-readable reason
// if that is the case. See allowedSubcommandsPerKubectlCommand.
func disallowedSubcommandRequested(parsed kubectlArguments) (string, bool) {
	allowedSubcommands, restricted := allowedSubcommandsPerKubectlCommand[parsed.kubectlCommand]
	if !restricted {
		return "", false
	}
	requestedSubcommand := ""
	if len(parsed.positionalArguments) > 0 {
		requestedSubcommand = parsed.positionalArguments[0]
	}
	if slices.Contains(allowedSubcommands, requestedSubcommand) {
		return "", false
	}
	if slices.Equal(allowedSubcommands, []string{""}) {
		return fmt.Sprintf(
			"the kubectl command %q may only be used without additional subcommands, but got %q",
			parsed.kubectlCommand,
			requestedSubcommand,
		), true
	}
	if requestedSubcommand == "" {
		return fmt.Sprintf(
			"the kubectl command %q is only allowed without a subcommand, but the subcommand was %q",
			parsed.kubectlCommand,
			strings.Join(allowedSubcommands, "\" or \""),
		), true
	}
	return fmt.Sprintf(
		"the kubectl command %q is only allowed with the subcommand %q, but the subcommand was %q",
		parsed.kubectlCommand,
		strings.Join(allowedSubcommands, "\" or \""),
		requestedSubcommand,
	), true
}

// describeRequested reports whether the kubectl arguments describe a resource, returning a human-readable reason when
// they do. The describer renders a resource in a text format that is not meant to be parsed and for which no parser is
// available, so the connector cannot locate the credentials in its output in order to redact them.
//
// This holds for every resource type, not only for the ones whose schema is known to have a credential field: a
// third-party custom resource can carry a credential just as well, and "kubectl describe" prints the annotations of any
// resource, including the verbatim copy of the applied manifest that "kubectl apply" leaves in
// "kubectl.kubernetes.io/last-applied-configuration".
func describeRequested(parsed kubectlArguments) (string, bool) {
	if parsed.kubectlCommand != "describe" {
		return "", false
	}
	return "\"kubectl describe\" is not supported, because it renders a resource in a text format the connector " +
		"cannot parse, so the credentials a resource may contain cannot be redacted from its output; read the " +
		"resource with \"kubectl get ... -o yaml\" or \"-o json\" instead, which returns the same content with its " +
		"credentials redacted, and its events with \"kubectl events --for <resource-type>/<name>\"", true
}

// describeOfSensitiveResourceRequested reports whether the kubectl arguments describe a sensitive resource, returning a
// human-readable reason when they do. Listing a secret and checking for the presence of a particular one are allowed
// (see sensitiveContentRequested), but describing one potentially exposes its content over:
// 1. kubectl describe secret prints the token of a "kubernetes.io/service-account-token" secret verbatim
// 2. kubectl describe secret prints the exact size of every other value, which is a length oracle over the value.
func describeOfSensitiveResourceRequested(parsed kubectlArguments) (string, bool) {
	if parsed.kubectlCommand != "describe" {
		return "", false
	}
	resource, targeted := targetedSensitiveResource(parsed)
	if !targeted {
		return "", false
	}
	return fmt.Sprintf(
		"describing a %s is not allowed, because \"kubectl describe\" prints the exact length of every value; "+
			"listing %ss or checking for the presence of a particular one with \"kubectl get %s <name>\" is supported",
		resource.displayName,
		resource.displayName,
		resource.displayName,
	), true
}

// sensitiveContentRequested reports whether the kubectl arguments would read the contents of a sensitive resource,
// returning a human-readable reason when they do. The default RBAC permissions disallow any access to secrets
// outright, even checking for the presence of a secret is not possible. However, overriding the default RBAC
// permissions with a custom cluster role is possible, and sensitiveContentRequested adds defense in-depth for those
// setups.
//
// Listing secrets (e.g. `kubectl get secrets`) and checking for the presence of a particular one
// (`kubectl get secret <name>`) are allowed (if the corresponding RBAC permissions are granted); serializing the data
// via an output format such as -o yaml/json/jsonpath/go-template/custom-columns (or --template) is not. This is a
// fail-closed check: output formats that could expose the data are rejected even if a particular invocation would only
// read metadata, and a repeated output flag is rejected if any of its occurrences would expose the data.
func sensitiveContentRequested(parsed kubectlArguments) (string, bool) {
	resource, targeted := targetedSensitiveResource(parsed)
	if !targeted {
		return "", false
	}
	if parsed.outputIsContentFree() {
		return "", false
	}
	return fmt.Sprintf(
		"reading the contents of a %s is not allowed; listing %ss or checking for the presence of a particular %s is "+
			"supported, but serializing its data (e.g. via -o yaml/json/jsonpath/go-template/custom-columns) is not",
		resource.displayName,
		resource.displayName,
		resource.displayName,
	), true
}

// targetedSensitiveResource returns the guard for the first sensitive resource the kubectl arguments reference.
func targetedSensitiveResource(parsed kubectlArguments) (sensitiveResource, bool) {
	for _, resourceType := range parsed.resourceTypes {
		if resource, isSensitive := lookupSensitiveResourceType(resourceType); isSensitive {
			return resource, true
		}
	}
	return sensitiveResource{}, false
}

// lookupSensitiveResourceType returns the guard for the given resource type, accepting the singular and plural forms as
// well as fully qualified forms such as "secrets.v1." (the API group/version suffix is ignored).
func lookupSensitiveResourceType(resourceType string) (sensitiveResource, bool) {
	resource, isSensitive := sensitiveResourceTypes[normalizeResourceType(resourceType)]
	return resource, isSensitive
}

// unsupportedOutputFormatRequested reports whether the kubectl arguments would render a resource in an output format
// the connector cannot hand out, returning a human-readable reason when they do: a format it does not know, or one
// whose result it cannot redact reliably. Every occurrence of -o/--output is checked, not just the effective (last)
// one, so that an argument list in which any occurrence is unsupported is rejected without replicating kubectl's
// precedence rules. The --template flag counts as go-template output even without -o, mirroring outputIsContentFree.
func unsupportedOutputFormatRequested(parsed kubectlArguments) (string, bool) {
	formats := parsed.outputFormats()
	if parsed.hasTemplateFlag() {
		// Appended, not prepended, so that an explicit -o is named in the rejection rather than the format --template
		// implies.
		formats = append(formats, goTemplateOutputFormat)
	}
	for _, format := range formats {
		switch knownOutputFormats[format] {
		case outputFormatUnknown:
			return fmt.Sprintf(
				"the kubectl output format %q is not allowed; %s",
				format,
				supportedOutputFormatsHint,
			), true
		case outputFormatUnredactable:
			return fmt.Sprintf(
				"the output format %q cannot be redacted reliably; %s",
				format,
				supportedOutputFormatsHint,
			), true
		}
	}
	return "", false
}

// unsafeSortByRequested reports whether the kubectl arguments sort a resource that can contain secrets by a field the
// response redacts, returning a human-readable reason when they do. kubectl evaluates a --sort-by expression against
// the unredacted resources, so the connector cannot redact what the expression exposes: sorting by a redacted field
// leaks its order, and a filter expression such as {.spec.containers[0].env[?(@.value>"S")].name} turns the presence
// of a match into a comparison oracle that reveals the value character by character over several requests. Every
// occurrence of the flag is checked, not just the effective (last) one, mirroring unsupportedOutputFormatRequested.
func unsafeSortByRequested(parsed kubectlArguments) (string, bool) {
	for _, expression := range parsed.valuesOf("sort-by") {
		if sortByExpressionIsSafe(expression) {
			continue
		}
		return fmt.Sprintf(
			"the --sort-by expression %q is not allowed; kubectl evaluates the expression against the resources "+
				"before the connector redacts them, so only a plain path below %s may be sorted by, except %q "+
				"(e.g. --sort-by=.metadata.name or --sort-by=.status.startTime)",
			expression,
			safeSortByPathPrefixesHumanReadable,
			unsafeSortByPathPrefix,
		), true
	}
	return "", false
}

// sortByExpressionIsSafe reports whether a --sort-by JSONPath expression addresses only fields that cannot hold a
// credential. It fails closed: anything it does not recognize as a plain path below safeSortByPathPrefixes is unsafe.
func sortByExpressionIsSafe(expression string) bool {
	path, normalized := normalizeSortByPath(expression)
	if !normalized || path == "" {
		return false
	}
	// A filter expression, a wildcard, a recursive descent or a second path can address any field of the resource,
	// including the ones the response redacts.
	if strings.ContainsAny(path, "?*{}") || strings.Contains(path, "..") {
		return false
	}
	if isSortByPathBelow(path, unsafeSortByPathPrefix) {
		return false
	}
	return slices.ContainsFunc(safeSortByPathPrefixes, func(prefix string) bool {
		return isSortByPathBelow(path, prefix)
	})
}

// isSortByPathBelow reports whether a normalized --sort-by path addresses the given field or anything below it.
func isSortByPathBelow(path string, prefix string) bool {
	return path == prefix ||
		strings.HasPrefix(path, prefix+".") ||
		strings.HasPrefix(path, prefix+"[")
}

// quotedSortByBracketSegment matches a quoted bracket segment of a JSONPath expression, e.g. ['annotations'] or
// ["annotations"], so that it can be rewritten to its dotted form.
var quotedSortByBracketSegment = regexp.MustCompile(`\[\s*'([^']*)'\s*\]|\[\s*"([^"]*)"\s*\]`)

// numericSortByIndexSegment matches a plain numeric index segment of a JSONPath expression, e.g. [0]. Such a segment
// selects an element of a list and cannot widen which field the expression addresses.
var numericSortByIndexSegment = regexp.MustCompile(`\[\d+\]`)

// normalizeSortByPath reduces a --sort-by expression to a plain dotted path: it strips the optional surrounding braces
// and the leading dot, and rewrites the quoted bracket segments of the JSONPath notation to their dotted form. So
// "{.metadata.name}", ".metadata.name" and "metadata.name" all yield "metadata.name", and "metadata['annotations']"
// yields "metadata.annotations".
//
// The bracket form has to be resolved because kubectl accepts it: it hands the expression to client-go's JSONPath
// parser (see RelaxedJSONPathExpression), which treats ['annotations'] and .annotations as the same step. Comparing
// only the dotted form let the bracket form address a field the dotted form is rejected for -
// "{.metadata['annotations']['kubectl.kubernetes.io/last-applied-configuration']}" passed the check for
// "metadata.annotations" and sorted by the very annotation that guard exists for.
//
// It reports false for an expression holding a bracket segment that is neither a quoted key nor a numeric index, since
// such a segment can address anything and the prefix comparison would not see what it resolves to.
func normalizeSortByPath(expression string) (string, bool) {
	path := strings.TrimSpace(expression)
	path = strings.TrimPrefix(path, "{")
	path = strings.TrimSuffix(path, "}")
	path = quotedSortByBracketSegment.ReplaceAllString(path, ".$1$2")
	path = strings.TrimPrefix(path, ".")
	if strings.ContainsAny(numericSortByIndexSegment.ReplaceAllString(path, ""), "[]") {
		return "", false
	}
	return path, true
}
