name: GKE Autopilot WorkloadAllowlist Check

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ci-workload-allowlist-check
  GKE_ZONE: europe-central2

concurrency:
  # This workflow uses a shared resource, allow only one execution at a time. Alternatively, we would need to add
  # steps to create a GKE Autopilot cluster on the fly and discard it after the GH action run.
  group: gke-ap-workload-allowlist-check-concurrency-group

jobs:
  check_workload_allowlists:
    name: Check WorkloadAllowlists
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      # set up the gcloud CLI
      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Note: We could potentially optimize this check by only running it when the Helm chart has changed.

      - name: run check
        env:
          GKE_AP_WORKLOAD_ALLOWLIST_CHECK_KUBECTX: TODO-which-test-cluster-should-we-use
        run: |-
          .github/workflows/scripts/gke-ap-workload-allowlist-check.sh
